1. PROJECT TITLE - TOURISM EXPERIENCE ANALYTICS: CLASSIFICATION, PREDICTION AND RECOMMENDATION SYSTEM.

2. PROJECT SUMMARY - 

    The Tourism Experience Analytics project is an end-to-end machine learning application that analyzes tourist behavior and delivers predictive insights and attraction recommendations through an interactive Streamlit web app.


    The system includes two supervised learning tasks:

    - Rating Prediction (Regression): A CatBoost Regressor predicts attraction ratings using contextual features and engineered aggregate statistics such as attraction-level averages and seasonal trends.
    - Visit Mode Prediction (Classification): A CatBoost Classifier predicts the likely visit mode (e.g., Family, Friends, Solo) based on geographic, attraction, temporal, and rating-related features.


    Additionally, an item-based collaborative filtering recommendation system suggests attractions using similarity patterns derived from user–attraction interactions (“People who visited X also visited Y”).
    
    The project demonstrates a complete ML pipeline consisting of data preprocessing, feature engineering, model training, artifact management and deployment, integrated into a single interactive application.

3. PROBLEM STATEMENT -
    
    Tourism agencies and travel platforms aim to enhance user experiences by leveraging data to provide personalized recommendations, predict user satisfaction, and classify potential user behavior. This project involves analyzing user preferences, travel patterns, and attraction features to achieve three primary objectives: regression, classification, and recommendation.

4. LOADING AND CHECKING THE DATAFRAMES -

In [3]:
# Importing the libraries
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [4]:
# To prevent truncating
pd.set_option('display.max_columns', None)

In [5]:
## Loading all the datasets

# Contains information about different cities, used to link users and attractions to specific geographical locations.
city = pd.read_csv('../dirty_data/City.csv', encoding='latin1')

# Contains information about the continents, helping to link users to their respective continents
continent = pd.read_csv('../dirty_data/Continent.csv')

# Contains information about countries, linking users and attractions to specific countries
country = pd.read_csv('../dirty_data/Country.csv', encoding='latin1')

# Contains information about regions within countries
attr = pd.read_csv('../dirty_data/Item.csv', encoding='latin1')

# Contains information about the types of visit modes users may have, such as business trips, family vacations or solo travel
mode = pd.read_csv('../dirty_data/Mode.csv')

# Contains information about regions within countries
region = pd.read_csv('../dirty_data/Region.csv')

# Contains information on user visits to various attractions, including ratings and visit details
txn = pd.read_csv('../dirty_data/Transaction.csv')

# Contains details about type of tourist attractions
attr_type = pd.read_csv('../dirty_data/Type.csv')

# Contains information about the users, such as their geographical location (continent, region, country, city)
user = pd.read_csv('../dirty_data/User.csv')

- Checking the dataframes of city, user, transactions, attractions and country, since these are larger than the rest of the dataframes and cannot be inspected manually.

    - Checking city dataframe

In [6]:
# Checking few rows
city.sample(7)

      CityId             CityName  CountryId
8237    8237            Dundonald        163
5828    5828               Bochum        125
1196    1196               Hoover         51
5870    5870        Gelsenkirchen        125
2403    2403  Shizuoka Prefecture         71
950      950               Denver         51
8610    8610               Mellor        163

In [7]:
# Checking the shape
city.shape

(9143, 3)

In [8]:
# Checking the info
city.info()

<class 'pandas.DataFrame'>
RangeIndex: 9143 entries, 0 to 9142
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CityId     9143 non-null   int64
 1   CityName   9142 non-null   str
 2   CountryId  9143 non-null   int64
dtypes: int64(2), str(1)
memory usage: 214.4 KB

In [9]:
# Checking the null values
city.isnull().sum()

CityId       0
CityName     1
CountryId    0
dtype: int64

In [10]:
# Checking for duplicates
city.duplicated().sum()

np.int64(0)

In [11]:
# Checking for duplicate cities
city[['CityName']].duplicated().sum()

np.int64(375)

    - Checking user dataframe

In [12]:
# Checking few rows
user.sample(7)

       UserId  ContinentId  RegionId  CountryId  CityId
23564   62618            2         8         51  1067.0
32356   84683            4        15        109  4934.0
21296   56950            2         8         51  1133.0
9713    27598            5        21        163  1743.0
8186    23321            5        21        163  9096.0
9231    26156            4        16        115  5671.0
15127   41396            4        15        109  5402.0

In [13]:
# Checking the shape
user.shape

(33530, 5)

In [14]:
# Checking the info
user.info()

<class 'pandas.DataFrame'>
RangeIndex: 33530 entries, 0 to 33529
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UserId       33530 non-null  int64
 1   ContinentId  33530 non-null  int64
 2   RegionId     33530 non-null  int64
 3   CountryId    33530 non-null  int64
 4   CityId       33526 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 1.3 MB

In [15]:
# Checking the null values
user.isnull().sum()

UserId         0
ContinentId    0
RegionId       0
CountryId      0
CityId         4
dtype: int64

In [16]:
# Checking for duplicates
user.duplicated().sum()

np.int64(0)

    - Checking txn dataframe

In [17]:
# Checking few rows
txn.sample(7)

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating
22629,35879,74412,2019,10,2,481,5
28643,48425,31525,2014,3,2,824,5
7558,11042,10048,2016,8,2,640,4
41931,108826,84648,2015,6,2,737,5
41648,108480,75072,2015,8,2,737,5
12203,17682,49210,2018,9,2,640,1
25524,41513,37919,2019,3,4,650,5

In [18]:
# Checking the shape
txn.shape

(52930, 7)

In [19]:
# Checking the info
txn.info()

<class 'pandas.DataFrame'>
RangeIndex: 52930 entries, 0 to 52929
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionId  52930 non-null  int64
 1   UserId         52930 non-null  int64
 2   VisitYear      52930 non-null  int64
 3   VisitMonth     52930 non-null  int64
 4   VisitMode      52930 non-null  int64
 5   AttractionId   52930 non-null  int64
 6   Rating         52930 non-null  int64
dtypes: int64(7)
memory usage: 2.8 MB

In [20]:
# Checking the description
txn.describe()

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating
count,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000,52930.000000
mean,70415.130474,45024.522596,2016.351899,6.633100,2.945759,759.663782,4.157699
std,66299.514206,25073.062199,1.732926,3.392979,1.000683,210.716111,0.970543
min,3.000000,14.000000,2013.000000,1.000000,1.000000,369.000000,1.000000
25%,19646.250000,23470.000000,2015.000000,4.000000,2.000000,640.000000,4.000000
50%,42770.500000,45533.500000,2016.000000,7.000000,3.000000,737.000000,4.000000
75%,105638.750000,66667.000000,2018.000000,9.000000,4.000000,841.000000,5.000000
max,211241.000000,88190.000000,2022.000000,12.000000,5.000000,1297.000000,5.000000

In [21]:
# Checking the null values
txn.isnull().sum()

TransactionId    0
UserId           0
VisitYear        0
VisitMonth       0
VisitMode        0
AttractionId     0
Rating           0
dtype: int64

In [22]:
# Checking for duplicates
txn.duplicated().sum()

np.int64(0)

    - Checking attr dataframe

In [23]:
# Checking few rows
attr.sample(7)

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
1359,2627,6168,Market,Local Bazaar - Limbach,"Main Street, Limbach, Slovakia"
1222,2490,5735,Temple,Grand Mosque - Mlini,"Main Street, Mlini, Croatia"
398,1666,260,Beach,Paradise Beach - San Ignacio,"Main Street, San Ignacio, Belize"
208,1476,89,Museum,Cultural Heritage Center - Tofinho,"Main Street, Tofinho, Mozambique"
1648,2916,7545,Temple,Grand Mosque - St.-Thibault-des-vignes,"Main Street, St.-Thibault-des-vignes, France"
1485,2753,6597,Market,Farmers' Market - Longyearbyen,"Main Street, Longyearbyen, Norway"
1083,2351,3614,Market,Night Market - Lop Buri,"Main Street, Lop Buri, Thailand"

In [24]:
# Checking the shape
attr.shape

(1698, 5)

In [25]:
# Checking the info
attr.info()

<class 'pandas.DataFrame'>
RangeIndex: 1698 entries, 0 to 1697
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AttractionId       1698 non-null   int64
 1   AttractionCityId   1698 non-null   int64
 2   AttractionTypeId   1698 non-null   str
 3   Attraction         1698 non-null   str
 4   AttractionAddress  1698 non-null   str
dtypes: int64(2), str(3)
memory usage: 66.5 KB

In [26]:
# Checking the null values
attr.isnull().sum()

AttractionId         0
AttractionCityId     0
AttractionTypeId     0
Attraction           0
AttractionAddress    0
dtype: int64

In [27]:
# Checking for duplicates
attr.duplicated().sum()

np.int64(0)

    - Checking country dataframe

In [28]:
# Checking few rows
country.sample(7)

     CountryId     Country  RegionId
16          16     Tunisia         3
9            9    Tanzania         2
48          48      Canada         8
65          65  Kyrgyzstan        10
18          18    Botswana         4
127        127      Latvia        17
92          92      Bhutan        13

In [29]:
# Checking the shape
country.shape

(165, 3)

In [30]:
# Checking the info
country.info()

<class 'pandas.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CountryId  165 non-null    int64
 1   Country    165 non-null    str
 2   RegionId   165 non-null    int64
dtypes: int64(2), str(1)
memory usage: 4.0 KB

In [31]:
# Checking the null values
country.isnull().sum()

CountryId    0
Country      0
RegionId     0
dtype: int64

In [32]:
# Checking for duplicates
country.duplicated().sum()

np.int64(0)

- Checking only the info for the rest of the dataframes.

In [33]:
# Info of attr_type dataframe
attr_type.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AttractionTypeId  17 non-null     int64
 1   AttractionType    17 non-null     str
dtypes: int64(1), str(1)
memory usage: 404.0 bytes

In [34]:
# Info of mode dataframe
mode.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VisitModeId  6 non-null      int64
 1   VisitMode    6 non-null      str
dtypes: int64(1), str(1)
memory usage: 228.0 bytes

In [35]:
# Info of continent dataframe
continent.info()

<class 'pandas.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ContinentId  6 non-null      float64
 1   Continent    6 non-null      str
dtypes: float64(1), str(1)
memory usage: 15.7 KB

In [36]:
# Info of region dataframe
region.info()

<class 'pandas.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Region       22 non-null     str
 1   RegionId     22 non-null     float64
 2   ContinentId  22 non-null     float64
dtypes: float64(2), str(1)
memory usage: 23.5 KB

- After a thorough and careful inspection of all the dataframes, the following points were observed -

    - The column "CityName" of city dataframe has one null value, so, that row needs to be removed.

    - The column "CityId" of user dataframe has four null values, so these rows need to be removed and the column is of float64 dtype which needs to be  changed to int64 for data consistency.

    - The column "AttractionTypeId" of attr dataframe contains string object as the id of few attractions which needs to be replaced by the actual id as per the attraction (for this we will refer attr_type dataframe that contains the unique id's for different types of attraction) and then convert the dtype of that column to int64 for data consistency.

    - The column "ContinentId" of continent dataframe has float64 dtype which needs to be converted to int64 dtype to maintain data consistency.
    
    - The column "ContinentId" and "RegionId" of region dataframe is of float64 dtype, which needs to be converted to int64 dtype for data consistency.

5. DATA CLEANING

a. Dataframe - city

In [37]:
# Removing rows with null values in 'city' dataframe
city = city.dropna()

# Removing rows with CityID column value is 0
city = city[city['CityId'] != 0]

# Checking for shape, null values and dtype in 'city' dataframe
print(city.shape)
print(city.isna().sum())
print(city.dtypes)

(9141, 3)
CityId       0
CityName     0
CountryId    0
dtype: int64
CityId       int64
CityName       str
CountryId    int64
dtype: object

b. Dataframe - user

In [38]:
# Removing rows from 'user' dataframe where RegionID column value is 0
user = user[user['RegionId'] != 0]

# Removing rows with null values in 'user' dataframe and converting CityID column to int64 dtype
user = user.dropna()
user['CityId'] = user['CityId'].astype(int)

# Checking for null values, shape and dtype in 'user' dataframe
print(user.shape)
print(user.isnull().sum())
print(user.dtypes)

(33507, 5)
UserId         0
ContinentId    0
RegionId       0
CountryId      0
CityId         0
dtype: int64
UserId         int64
ContinentId    int64
RegionId       int64
CountryId      int64
CityId         int64
dtype: object

c. Dataframe - continent

In [39]:
# Removing null values from 'continent' dataframe
continent = continent.dropna()

# Removing rows where value of ContinentID column is 0 
continent = continent[continent['ContinentId'] != 0]

# Changing the dtype of ContinentId column to int64 from 'continent' dataframe
continent['ContinentId'] = continent['ContinentId'].astype(int)

# Checking for null values, shape and dtypes in 'continent' dataframe
print(continent.shape)
print(continent.isna().sum())
print(continent.dtypes)

(5, 2)
ContinentId    0
Continent      0
dtype: int64
ContinentId    int64
Continent        str
dtype: object

d. Dataframe - region

In [40]:
# Removing null values from 'region' dataframe
region = region.dropna()

# Removing rows where value of ContinentID column is 0
region = region[region['ContinentId'] != 0]

# Changing the dtype of ContinentId and RegionId column from 'region' dataframe to int64
region['ContinentId'] = region['ContinentId'].astype(int)
region['RegionId'] = region['RegionId'].astype(int)

# Checking for null values, shape and dtypes in 'region' dataframe
print(region.shape)
print(region.isna().sum())
print(region.dtypes)

(21, 3)
Region         0
RegionId       0
ContinentId    0
dtype: int64
Region           str
RegionId       int64
ContinentId    int64
dtype: object

e. Dataframe - country

In [41]:
# Removing rows where CountryID column value is 0 in the 'country' dataframe
country = country[country['CountryId'] != 0]

# Checking for null values, shape and dtypes in 'country' dataframe
print(country.shape)
print(country.isnull().sum())
print(country.dtypes)

(164, 3)
CountryId    0
Country      0
RegionId     0
dtype: int64
CountryId    int64
Country        str
RegionId     int64
dtype: object

f. Dataframe - mode

In [42]:
# Removing rows where VisitModeID column value is 0 in the 'mode' dataframe
mode = mode[mode['VisitModeId'] != 0]

# Checking for null values, shape and dtypes in 'mode' dataframe
print(mode.shape)
print(mode.isnull().sum())
print(mode.dtypes)

(5, 2)
VisitModeId    0
VisitMode      0
dtype: int64
VisitModeId    int64
VisitMode        str
dtype: object

g. Dataframe - attr

In [43]:
# Removing rows where AttractionCityId column value is 0 in the 'attr' dataframe
attr = attr[attr['AttractionCityId'] != 0]

# Checking for null values, shape and dtypes in 'attr' dataframe
print(attr.shape)
print(attr.isnull().sum())
print(attr.dtypes)

(1694, 5)
AttractionId         0
AttractionCityId     0
AttractionTypeId     0
Attraction           0
AttractionAddress    0
dtype: int64
AttractionId         int64
AttractionCityId     int64
AttractionTypeId       str
Attraction             str
AttractionAddress      str
dtype: object

h. Dataframe - txn

In [44]:
# Renaming the column of VisitMode to VisitModeId
txn = txn.rename(columns={'VisitMode': 'VisitModeId'})

# Checking the name of the columns
txn.columns

Index(['TransactionId', 'UserId', 'VisitYear', 'VisitMonth', 'VisitModeId',
       'AttractionId', 'Rating'],
      dtype='str')

We will be creating two dataframes from the attr dataframe. One will contain only int64 objects in the "AttractionTypeId" column and the other column will have only string objects in the "AttractionTypeId" column. This will help clean the whole attr dataframe properly. After cleaning, we will merge both of them two form the original attr dataframe again.

In [45]:
# Creating attr_num that will contain int64 objects in the AttractionTypeID column
attr_num = attr[pd.to_numeric(attr['AttractionTypeId'], errors='coerce').notna()]

# Enforcing the dtype of the AttractionTypeID column to be int64
attr_num['AttractionTypeId'] = attr_num['AttractionTypeId'].astype(int)

# Checking few rows of the new dataframe
attr_num.sample(7)

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
11,888,2,61,Bromo Tengger Semeru National Park,"Asrikaton - Pakis, Malang 65100 Indonesia"
17,947,2,91,Mount Semeru Volcano,Malang Lumajang
24,1220,3,10,Ramayana Ballet at Prambanan,Sleman
10,877,2,13,Balekambang Beach,Malang District
16,937,2,72,Malang City Square,"Jl. Merdeka Utara, Malang 65119 Indonesia"
7,749,1,93,Tegenungan Waterfall,"Jl. Raya Tegenungan, Kemenuh, Ubud 80581 Indon..."
1,481,1,13,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia"

In [46]:
# Checking the shape and info of the attr_num dataframe
print(attr_num.shape)
print(attr_num.info())

(30, 5)
<class 'pandas.DataFrame'>
Index: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AttractionId       30 non-null     int64
 1   AttractionCityId   30 non-null     int64
 2   AttractionTypeId   30 non-null     int64
 3   Attraction         30 non-null     str
 4   AttractionAddress  30 non-null     str
dtypes: int64(3), str(2)
memory usage: 1.4 KB
None

In [47]:
# Creating attr_str that will contain string objects in the AttractionTypeID column
attr_str = attr[pd.to_numeric(attr['AttractionTypeId'], errors='coerce').isna()]

# Checking few rows of the new dataframe
attr_str.sample(7)

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
1103,2371,5150,Museum,Art Gallery - St Peters,"Main Street, St Peters, Australia"
937,2205,2937,Museum,Science Museum - Dharan,"Main Street, Dharan, Nepal"
357,1625,246,Market,Farmers' Market - San Juan,"Main Street, San Juan, Puerto Rico"
444,1712,295,Beach,Paradise Beach - San Juan del Sur,"Main Street, San Juan del Sur, Nicaragua"
1421,2689,6385,Temple,Grand Mosque - Novosibirsk,"Main Street, Novosibirsk, Russia"
1441,2709,6402,Museum,Art Gallery - Dnipro,"Main Street, Dnipro, Ukraine"
1014,2282,3298,Beach,Sunset Cove - Laos,"Main Street, Laos, Laos"

In [48]:
# Checking the shape and info of the attr_str dataframe
print(attr_str.shape)
print(attr_str.info())

(1664, 5)
<class 'pandas.DataFrame'>
Index: 1664 entries, 34 to 1697
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AttractionId       1664 non-null   int64
 1   AttractionCityId   1664 non-null   int64
 2   AttractionTypeId   1664 non-null   str
 3   Attraction         1664 non-null   str
 4   AttractionAddress  1664 non-null   str
dtypes: int64(2), str(3)
memory usage: 78.0 KB
None

The sample of attr_str from above shows that the "AttractionTypeID" column has categorical entries as the ID which is incorrect for this task. We will be changing those entries with the actual ID's by referring to the attr_type dataframe that shows which ID should be associated with a particular type of attraction.

To achieve this, we will define a function which will look for certain words that describe what type of attraction that is and then it will assign the particular ID for it.

In [49]:
# Helper Function
def classify(name, id):
    name = name.lower()

    # For Temple category in AttractionTypeId column
    if any (x in name for x in ['cathedral', 'temple', 'mosque', 'shrine']):
        return 76    # Religious Sites
    

    # For Park category in AttractionTypeId column, there are few rows with national park, we will deal with them later
    # Here, we will deal with rows containing botanical garden, eco park and wildlife reserve, as these three come under the same ID
    if any (y in name for y in ['botanical garden', 'eco park', 'wildlife reserve']):
        return 63    # Nature & Wildlife Areas
    

    # For Museum category in AttractionTypeId column, there are rows that include
    # cultural heritage places, art gallery, history museum and science museum, we will deal with them accordingly
    # 1. Art Gallery and Science Museum
    if any (z in name for z in ['art gallery', 'science museum']):
        return 84    # Speciality Museums
    
    # 2. History Museum
    if 'history museum' in name:
        return 45    # History Museums
    
    # 3. Cultural Heritage Center
    if 'cultural heritage center' in name:
        return 72    # Points of Interest & Landmarks
    

    # For Market category in AttractionTypeId column
    if any (a in name for a in ['market', 'bazaar']):
        return 34    # Flea & Street Markets


    # For Beach category in AttractionTypeId column
    if any (b in name for b in ['beach', 'bay', 'cove']):
        return 13    # Beaches


    # For any remaining row that has National Park in it
    if 'national park' in name:
        return 61    # National Parks
    

    return id

In [50]:
# Applying the function (also enforcing the dtype to be int64)
attr_str['AttractionTypeId'] = attr_str.apply(lambda c: classify(c['Attraction'], c['AttractionTypeId']), axis=1).astype(int)

In [51]:
# Checking the first few rows
attr_str.head()

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
34,1302,2,84,Art Gallery - South Region,"Main Street, South Region, Cameroon"
35,1303,2,34,Farmers' Market - South Region,"Main Street, South Region, Cameroon"
36,1304,2,34,Night Market - South Region,"Main Street, South Region, Cameroon"
37,1305,2,76,Cathedral - South Region,"Main Street, South Region, Cameroon"
38,1306,1,63,Eco Park - Douala,"Main Street, Douala, Cameroon"

In [52]:
# Checking random rows
attr_str.sample(7)

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
694,1962,2453,13,Sunset Cove - Banqiao,"Main Street, Banqiao, Taiwan"
1532,2800,6741,45,History Museum - Sofia Region,"Main Street, Sofia Region, Bulgaria"
525,1793,2163,63,Botanical Garden - Santa Cruz,"Main Street, Santa Cruz, Bolivia"
1528,2796,6743,72,Cultural Heritage Center - Varna,"Main Street, Varna, Bulgaria"
585,1853,2245,84,Art Gallery - Aguas Calientes,"Main Street, Aguas Calientes, Peru"
1204,2472,5688,34,Local Bazaar - Europe,"Main Street, Europe, Europe"
1174,2442,5680,13,Sunset Cove - Lae,"Main Street, Lae, Papua New Guinea"

In [53]:
# Checking last few rows
attr_str.tail()

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
1693,2961,8154,76,Ancient Temple - Churchdown,"Main Street, Churchdown, United Kingdom"
1694,2962,9142,76,Ancient Temple - Sanaa,"Main Street, Sanaa, Yemen"
1695,2963,9142,84,Science Museum - Sanaa,"Main Street, Sanaa, Yemen"
1696,2964,9142,63,Botanical Garden - Sanaa,"Main Street, Sanaa, Yemen"
1697,2965,9142,63,Botanical Garden - Sanaa,"Main Street, Sanaa, Yemen"

In [54]:
# Checking row that has both "Eco Park" and "National Park" in its name
attr_str[attr_str['Attraction'].str.contains("National Park") & attr_str['Attraction'].str.contains("Eco Park")]

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
415,1683,261,63,Eco Park - Arenal Volcano National Park,"Main Street, Arenal Volcano National Park, Cos..."

In [55]:
# Checking row that has both "Market" and "National Park" in its name
attr_str[attr_str['Attraction'].str.contains("National Park") & attr_str['Attraction'].str.contains("Market")]

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
416,1684,261,34,Farmers' Market - Arenal Volcano National Park,"Main Street, Arenal Volcano National Park, Cos..."

In [56]:
# Checking the info the updated attr_str dataframe
attr_str.info()

<class 'pandas.DataFrame'>
Index: 1664 entries, 34 to 1697
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AttractionId       1664 non-null   int64
 1   AttractionCityId   1664 non-null   int64
 2   AttractionTypeId   1664 non-null   int64
 3   Attraction         1664 non-null   str
 4   AttractionAddress  1664 non-null   str
dtypes: int64(3), str(2)
memory usage: 78.0 KB

In [57]:
# Now that the necessary changes have been made to the attr_str dataframe, we will merge it with attr_num dataframe
attr_clean = pd.concat([attr_num, attr_str], axis=0)

In [58]:
# Checking few rows of the attr_clean dataframe
attr_clean.sample(10)

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
736,2004,2496,13,Crystal Bay - Isfahan,"Main Street, Isfahan, Iran"
512,1780,2148,34,Flea Market - Argentina,"Main Street, Argentina, Argentina"
1471,2739,6558,34,Night Market - ReykjavÃ­k,"Main Street, ReykjavÃ­k, Iceland"
409,1677,269,61,National Park - Manuel Antonio,"Main Street, Manuel Antonio, Costa Rica"
260,1528,219,45,History Museum - Ilorin,"Main Street, Ilorin, NIGERIA"
5,737,1,76,Tanah Lot Temple,"Kecamatan Kediri, Kabupaten Tabanan, Beraban 8..."
1695,2963,9142,84,Science Museum - Sanaa,"Main Street, Sanaa, Yemen"
1685,2953,8459,76,Ancient Temple - Isle of Mull,"Main Street, Isle of Mull, United Kingdom"
557,1825,2235,72,Cultural Heritage Center - Popayan,"Main Street, Popayan, Colombia"
733,2001,2495,34,Farmers' Market - Iran,"Main Street, Iran, Iran"

In [59]:
# Re-enforcing the AttractionTypeID column to be of int64 dtype
attr_clean['AttractionTypeId'] = attr_clean['AttractionTypeId'].astype(int)

In [60]:
# Checking the info of attr_clean
attr_clean.info()

<class 'pandas.DataFrame'>
Index: 1694 entries, 0 to 1697
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AttractionId       1694 non-null   int64
 1   AttractionCityId   1694 non-null   int64
 2   AttractionTypeId   1694 non-null   int64
 3   Attraction         1694 non-null   str
 4   AttractionAddress  1694 non-null   str
dtypes: int64(3), str(2)
memory usage: 79.4 KB

Now that all the dataframes have been cleaned, we will merge them all together.

In [61]:
# Merging
df = txn.merge(user[['UserId', 'CityId']], on='UserId', how='left')
df = df.merge(city, on='CityId', how='left')
df = df.merge(country, on='CountryId', how='left')
df = df.merge(region, on='RegionId', how='left')
df = df.merge(continent, on='ContinentId', how='left')
df = df.merge(attr_clean[['AttractionId', 'AttractionCityId', 'AttractionTypeId', 'Attraction']], on='AttractionId', how='left')
df = df.merge(attr_type, on='AttractionTypeId', how='left')
df = df.merge(mode, on='VisitModeId', how='left')

# Checking few rows of the merged dataframe
df.sample(7)

,TransactionId,UserId,VisitYear,VisitMonth,VisitModeId,AttractionId,Rating,CityId,CityName,CountryId,Country,RegionId,Region,ContinentId,Continent,AttractionCityId,AttractionTypeId,Attraction,AttractionType,VisitMode
5339,7808,57649,2017,3,3,640,1,6128.0,Brasov,131.0,Romania,17.0,Central Europe,5.0,Europe,1,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas,Family
45217,194925,20112,2019,3,1,888,5,3260.0,Surabaya,101.0,Indonesia,14.0,South East Asia,3.0,Asia,2,61,Bromo Tengger Semeru National Park,National Parks,Business
48344,202277,40102,2018,6,4,1171,5,1133.0,Greenwich,51.0,United States,8.0,Northern America,2.0,America,3,91,Merapi Volcano,Volcanos,Friends
16091,24448,41274,2016,10,3,841,5,5488.0,Auckland Central,115.0,New Zealand,16.0,Oceania,4.0,Australia & Oceania,1,92,Waterbom Bali,Water Parks,Family
40657,107028,77359,2017,3,2,737,5,5267.0,Townsville,109.0,Australia,15.0,Australia,4.0,Australia & Oceania,1,76,Tanah Lot Temple,Religious Sites,Couples
24536,38514,29306,2014,2,3,481,4,6701.0,Stockholm,145.0,Sweden,19.0,Northern Europe,5.0,Europe,1,13,Nusa Dua Beach,Beaches,Family
1301,2309,3418,2018,6,2,640,2,8936.0,Strathaven,163.0,United Kingdom,21.0,Western Europe,5.0,Europe,1,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas,Couples

In [62]:
# Checking the shape and info of the merged dataframe
print('Shape of df:', df.shape)
print('\nInfo of df:', df.info())

Shape of df: (52930, 20)
<class 'pandas.DataFrame'>
RangeIndex: 52930 entries, 0 to 52929
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TransactionId     52930 non-null  int64
 1   UserId            52930 non-null  int64
 2   VisitYear         52930 non-null  int64
 3   VisitMonth        52930 non-null  int64
 4   VisitModeId       52930 non-null  int64
 5   AttractionId      52930 non-null  int64
 6   Rating            52930 non-null  int64
 7   CityId            52890 non-null  float64
 8   CityName          52890 non-null  str
 9   CountryId         52890 non-null  float64
 10  Country           52890 non-null  str
 11  RegionId          52890 non-null  float64
 12  Region            52890 non-null  str
 13  ContinentId       52890 non-null  float64
 14  Continent         52890 non-null  str
 15  AttractionCityId  52930 non-null  int64
 16  AttractionTypeId  52930 non-null  int64
 17  Attraction        52930 non-null  str
 18  AttractionType    52930 non-null  str
 19  VisitMode         52930 non-null  str
dtypes: float64(4), int64(9), str(7)
memory usage: 8.1 MB

Info of df: None

In [63]:
# Checking the null values of the merged dataframe
df.isna().sum()

TransactionId        0
UserId               0
VisitYear            0
VisitMonth           0
VisitModeId          0
AttractionId         0
Rating               0
CityId              40
CityName            40
CountryId           40
Country             40
RegionId            40
Region              40
ContinentId         40
Continent           40
AttractionCityId     0
AttractionTypeId     0
Attraction           0
AttractionType       0
VisitMode            0
dtype: int64

In [64]:
# Checking the data type of each column of df
df.dtypes

TransactionId         int64
UserId                int64
VisitYear             int64
VisitMonth            int64
VisitModeId           int64
AttractionId          int64
Rating                int64
CityId              float64
CityName                str
CountryId           float64
Country                 str
RegionId            float64
Region                  str
ContinentId         float64
Continent               str
AttractionCityId      int64
AttractionTypeId      int64
Attraction              str
AttractionType          str
VisitMode               str
dtype: object

Despite earlier cleaning of all the dataframes before merging and also verifying that all dataframes had zero null values and the intended dtypes, we see that rows of few columns have null values and therefore to accomodate them the dtype has also changed from int64 to float64. This happened because the txn dataframe was the 'left' dataframe when it was merged with the user dataframe (how='left' was used) and before merging we removed the four rows with null values from user dataframe, so when merging, the rows of txn dataframe that had same common values as the ones removed due to cleaning the user dataframe, remained as it was, while the rows in the user dataframe for those values registered null values. So, to accomodate these null values, pandas, by default, changed the dtype of those numeric columns to float64.

We will clean this new merged dataframe now and save it in CSV format.

In [65]:
# Removing the null values
df = df.dropna()

# Checking the shape and null values
print(df.shape)
print(df.isna().sum())

(52890, 20)
TransactionId       0
UserId              0
VisitYear           0
VisitMonth          0
VisitModeId         0
AttractionId        0
Rating              0
CityId              0
CityName            0
CountryId           0
Country             0
RegionId            0
Region              0
ContinentId         0
Continent           0
AttractionCityId    0
AttractionTypeId    0
Attraction          0
AttractionType      0
VisitMode           0
dtype: int64

In [66]:
# Converting the numeric columns to int64 dtype
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
df[numeric_columns] = df[numeric_columns].astype(int)

# Mapping the name of months to their respective numbers in the VisitMonth column
month_mapping = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'}
df['Month'] = df['VisitMonth'].map(month_mapping)

# Checking the data types after conversion
df.dtypes

TransactionId       int64
UserId              int64
VisitYear           int64
VisitMonth          int64
VisitModeId         int64
AttractionId        int64
Rating              int64
CityId              int64
CityName              str
CountryId           int64
Country               str
RegionId            int64
Region                str
ContinentId         int64
Continent             str
AttractionCityId    int64
AttractionTypeId    int64
Attraction            str
AttractionType        str
VisitMode             str
Month                 str
dtype: object

6. SAVING THE DATAFRAME 'df' IN CSV FORMAT

In [ ]:
df.to_csv('../clean_data/df_clean.csv', index=False)