In this file, we will work on the classification task that will help predict the Visit Mode of any particular user using various inputs.

In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Loading the dataset
df_clean = pd.read_csv('../clean_data/df_clean.csv')

# Checking few sample rows of the dataset
df_clean.sample(7)

,TransactionId,UserId,VisitYear,VisitMonth,VisitModeId,AttractionId,Rating,CityId,CityName,CountryId,...,RegionId,Region,ContinentId,Continent,AttractionCityId,AttractionTypeId,Attraction,AttractionType,VisitMode,Month
33592,69935,74287,2018,4,2,748,5,2263,Ulaanbaatar,66,...,10,Central Asia,3,Asia,1,72,Tegalalang Rice Terrace,Points of Interest & Landmarks,Couples,April
38097,100240,72941,2018,1,2,749,4,3164,Medan,101,...,14,South East Asia,3,Asia,1,93,Tegenungan Waterfall,Waterfalls,Couples,January
21506,34019,63923,2016,7,3,673,2,7153,Puerto de la Cruz,157,...,20,Southern Europe,5,Europe,1,13,Seminyak Beach,Beaches,Family,July
24085,37971,82946,2015,11,2,481,4,1676,Phoenix,51,...,8,Northern America,2,America,1,13,Nusa Dua Beach,Beaches,Couples,November
16606,25209,65903,2016,8,3,841,5,3687,Adelaide,109,...,15,Australia,4,Australia & Oceania,1,92,Waterbom Bali,Water Parks,Family,August
22181,34907,28533,2014,8,2,673,4,4940,Perth,109,...,15,Australia,4,Australia & Oceania,1,13,Seminyak Beach,Beaches,Couples,August
1638,2748,55312,2017,4,2,640,5,426,London,48,...,8,Northern America,2,America,1,63,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas,Couples,April

In [3]:
# Checking the name of the columns
df_clean.columns

Index(['TransactionId', 'UserId', 'VisitYear', 'VisitMonth', 'VisitModeId',
       'AttractionId', 'Rating', 'CityId', 'CityName', 'CountryId', 'Country',
       'RegionId', 'Region', 'ContinentId', 'Continent', 'AttractionCityId',
       'AttractionTypeId', 'Attraction', 'AttractionType', 'VisitMode',
       'Month'],
      dtype='object')

In [ ]:
# Creating a new dataframe with only the columns we need for the classification task
df_clf = df_clean[['Month', 'CityName', 'Country', 'Region', 'Continent', 'Attraction', 'AttractionType', 'Rating', 'VisitMode']].copy()

# Checking the rows of this dataframe
df_clf.sample(7)

,Month,CityName,Country,Region,Continent,Attraction,AttractionType,Rating,VisitMode
875,June,Miami,United States,Northern America,America,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas,5,Couples
11457,January,Melbourne,United States,Northern America,America,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas,4,Couples
24902,March,New York City,United States,Northern America,America,Sanur Beach,Beaches,5,Couples
23328,July,Melbourne,United States,Northern America,America,Nusa Dua Beach,Beaches,5,Couples
13695,September,Whitianga,New Zealand,Oceania,Australia & Oceania,Waterbom Bali,Water Parks,5,Family
43426,January,Spalding,United Kingdom,Western Europe,Europe,Kuta Beach - Bali,Beaches,3,Couples
3864,January,Manama,Bahrain,Middle East,Asia,Sacred Monkey Forest Sanctuary,Nature & Wildlife Areas,5,Couples

In [5]:
# Train test split
from sklearn.model_selection import train_test_split

# Separating the features and the target variable
x = df_clf.drop('VisitMode', axis=1)
y = df_clf['VisitMode']

# Splitting the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

In [6]:
# Creating a list of the categorical columns
cat_cols = ['Month', 'CityName', 'Country', 'Region', 'Continent', 'Attraction', 'AttractionType']

# Creating cat_features to be used later in the CatBoostClassifier model
cat_features = [x_train.columns.get_loc(col) for col in cat_cols]

In [7]:
# For LightGBM we will convert the categorical columns to category dtype
for c in cat_cols:
    x_train[c] = x_train[c].astype('category')
    x_test[c] = x_test[c].astype('category')

In [9]:
# Importing the necessary libraries
import mlflow
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score, precision_score, recall_score

In [10]:
# We  will be using class_weight to handle the class imbalance in the target variable
# This increases the weight of the minority classes
from sklearn.utils.class_weight import compute_class_weight
classes = np.unique(y_train)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
class_weights = dict(zip(classes, weights))

- CatBoost Models' MLFlow run and training.

In [11]:
# Setting the MLflow experiment name
mlflow.set_experiment('Tourism_VisitMode_Classification')

# Starting the MLflow run
with mlflow.start_run(run_name='CatBoostClassifier_1'):

    # Initializing the CatBoostClassifier model
    cat1 = CatBoostClassifier(iterations=300,
                              depth=6,
                              learning_rate=0.1,
                              loss_function='MultiClass',
                              class_weights=class_weights,
                              random_seed=42)
    
    # Fitting the model on the training data
    cat1.fit(x_train, y_train, cat_features=cat_features, eval_set=(x_test, y_test), verbose=1)
    
    # Predicting the Visit Mode on the test data
    y_pred = cat1.predict(x_test)
    
    # Evaluating the model performance
    f1 = f1_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    precision = precision_score(y_test, y_pred, average='weighted')
    
    # Logging the parameters and metrics to MLflow
    mlflow.log_param('model_name', 'CatBoostClassifier')
    mlflow.log_param('iterations', 300)
    mlflow.log_param('depth', 6)
    mlflow.log_param('learning_rate', 0.1)
    mlflow.log_metric('f1_score', f1)
    mlflow.log_metric('recall_score', recall)
    mlflow.log_metric('precision_score', precision)

    # Logging the model to MLflow
    mlflow.catboost.log_model(cat1, 'cat1')

2026/02/21 20:20:48 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.schemas
2026/02/21 20:20:48 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.tables
2026/02/21 20:20:48 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.types
2026/02/21 20:20:48 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.constraints
2026/02/21 20:20:48 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.defaults
2026/02/21 20:20:48 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.comments
2026/02/21 20:20:50 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/02/21 20:20:50 INFO alembic.runtime.migration: Will assume non-transactional DDL.

0:	learn: 1.5852302	test: 1.5868203	best: 1.5868203 (0)	total: 1.36s	remaining: 6m 47s
1:	learn: 1.5687132	test: 1.5710907	best: 1.5710907 (1)	total: 2.66s	remaining: 6m 36s
2:	learn: 1.5546658	test: 1.5579001	best: 1.5579001 (2)	total: 3.6s	remaining: 5m 56s
3:	learn: 1.5429744	test: 1.5490818	best: 1.5490818 (3)	total: 4.6s	remaining: 5m 40s
4:	learn: 1.5307486	test: 1.5366444	best: 1.5366444 (4)	total: 5.33s	remaining: 5m 14s
5:	learn: 1.5205717	test: 1.5281319	best: 1.5281319 (5)	total: 6s	remaining: 4m 53s
6:	learn: 1.5100603	test: 1.5193075	best: 1.5193075 (6)	total: 6.7s	remaining: 4m 40s
7:	learn: 1.5010809	test: 1.5125871	best: 1.5125871 (7)	total: 7.35s	remaining: 4m 28s
8:	learn: 1.4937494	test: 1.5072987	best: 1.5072987 (8)	total: 7.97s	remaining: 4m 17s
9:	learn: 1.4886236	test: 1.5037879	best: 1.5037879 (9)	total: 8.75s	remaining: 4m 13s
10:	learn: 1.4831570	test: 1.5008707	best: 1.5008707 (10)	total: 9.51s	remaining: 4m 9s
11:	learn: 1.4775263	test: 1.4966192	best: 1.4966192 (11)	total: 10.2s	remaining: 4m 3s
12:	learn: 1.4735294	test: 1.4938430	best: 1.4938430 (12)	total: 10.8s	remaining: 3m 59s
13:	learn: 1.4688748	test: 1.4899538	best: 1.4899538 (13)	total: 11.6s	remaining: 3m 56s
14:	learn: 1.4652888	test: 1.4879878	best: 1.4879878 (14)	total: 12.2s	remaining: 3m 51s
15:	learn: 1.4609141	test: 1.4857031	best: 1.4857031 (15)	total: 12.8s	remaining: 3m 47s
16:	learn: 1.4590977	test: 1.4845404	best: 1.4845404 (16)	total: 13.6s	remaining: 3m 45s
17:	learn: 1.4560721	test: 1.4820591	best: 1.4820591 (17)	total: 14.2s	remaining: 3m 42s
18:	learn: 1.4536845	test: 1.4805557	best: 1.4805557 (18)	total: 14.8s	remaining: 3m 38s
19:	learn: 1.4512660	test: 1.4796052	best: 1.4796052 (19)	total: 15.4s	remaining: 3m 36s
20:	learn: 1.4485720	test: 1.4780181	best: 1.4780181 (20)	total: 16s	remaining: 3m 33s
21:	learn: 1.4457368	test: 1.4751332	best: 1.4751332 (21)	total: 16.6s	remaining: 3m 29s
22:	learn: 1.4410791	test: 1.4724614	best: 1.4724614 (22)	total: 17.2s	remaining: 3m 26s
23:	learn: 1.4367777	test: 1.4694215	best: 1.4694215 (23)	total: 17.8s	remaining: 3m 24s
24:	learn: 1.4341316	test: 1.4672869	best: 1.4672869 (24)	total: 18.4s	remaining: 3m 22s
25:	learn: 1.4332201	test: 1.4662336	best: 1.4662336 (25)	total: 18.7s	remaining: 3m 17s
26:	learn: 1.4291701	test: 1.4628348	best: 1.4628348 (26)	total: 19.3s	remaining: 3m 15s
27:	learn: 1.4266048	test: 1.4624184	best: 1.4624184 (27)	total: 20.1s	remaining: 3m 14s
28:	learn: 1.4239323	test: 1.4590919	best: 1.4590919 (28)	total: 20.6s	remaining: 3m 12s
29:	learn: 1.4217804	test: 1.4572956	best: 1.4572956 (29)	total: 21.3s	remaining: 3m 12s
30:	learn: 1.4203861	test: 1.4556086	best: 1.4556086 (30)	total: 21.7s	remaining: 3m 8s
31:	learn: 1.4179734	test: 1.4546500	best: 1.4546500 (31)	total: 22.6s	remaining: 3m 8s
32:	learn: 1.4140179	test: 1.4496193	best: 1.4496193 (32)	total: 23.2s	remaining: 3m 7s
33:	learn: 1.4114446	test: 1.4484358	best: 1.4484358 (33)	total: 23.9s	remaining: 3m 6s
34:	learn: 1.4079560	test: 1.4451230	best: 1.4451230 (34)	total: 24.5s	remaining: 3m 5s
35:	learn: 1.4066721	test: 1.4447848	best: 1.4447848 (35)	total: 25.1s	remaining: 3m 4s
36:	learn: 1.4014446	test: 1.4380641	best: 1.4380641 (36)	total: 25.7s	remaining: 3m 2s
37:	learn: 1.3979149	test: 1.4337813	best: 1.4337813 (37)	total: 26.2s	remaining: 3m
38:	learn: 1.3958657	test: 1.4324800	best: 1.4324800 (38)	total: 26.9s	remaining: 2m 59s
39:	learn: 1.3949721	test: 1.4321849	best: 1.4321849 (39)	total: 27.5s	remaining: 2m 58s
40:	learn: 1.3938165	test: 1.4321319	best: 1.4321319 (40)	total: 28.2s	remaining: 2m 58s
41:	learn: 1.3917057	test: 1.4294701	best: 1.4294701 (41)	total: 28.8s	remaining: 2m 57s
42:	learn: 1.3917056	test: 1.4294700	best: 1.4294700 (42)	total: 29s	remaining: 2m 53s
43:	learn: 1.3914861	test: 1.4287821	best: 1.4287821 (43)	total: 29.3s	remaining: 2m 50s
44:	learn: 1.3887901	test: 1.4276703	best: 1.4276703 (44)	total: 30s	remaining: 2m 50s
45:	learn: 1.3873137	test: 1.4271904	best: 1.4271904 (45)	total: 30.6s	remaining: 2m 49s
46:	learn: 1.3858271	test: 1.4250460	best: 1.4250460 (46)	total: 31.2s	remaining: 2m 48s
47:	learn: 1.3846270	test: 1.4247114	best: 1.4247114 (47)	total: 31.9s	remaining: 2m 47s
48:	learn: 1.3840793	test: 1.4247527	best: 1.4247114 (47)	total: 32.5s	remaining: 2m 46s
49:	learn: 1.3828262	test: 1.4252246	best: 1.4247114 (47)	total: 33.1s	remaining: 2m 45s
50:	learn: 1.3806279	test: 1.4227834	best: 1.4227834 (50)	total: 33.6s	remaining: 2m 44s
51:	learn: 1.3788931	test: 1.4222485	best: 1.4222485 (51)	total: 34.3s	remaining: 2m 43s
52:	learn: 1.3772925	test: 1.4211988	best: 1.4211988 (52)	total: 35s	remaining: 2m 43s
53:	learn: 1.3762134	test: 1.4209423	best: 1.4209423 (53)	total: 35.9s	remaining: 2m 43s
54:	learn: 1.3737225	test: 1.4192188	best: 1.4192188 (54)	total: 36.6s	remaining: 2m 43s
55:	learn: 1.3723631	test: 1.4180121	best: 1.4180121 (55)	total: 37.4s	remaining: 2m 42s
56:	learn: 1.3697850	test: 1.4154137	best: 1.4154137 (56)	total: 38s	remaining: 2m 41s
57:	learn: 1.3687337	test: 1.4149633	best: 1.4149633 (57)	total: 38.6s	remaining: 2m 40s
58:	learn: 1.3667630	test: 1.4147283	best: 1.4147283 (58)	total: 39.3s	remaining: 2m 40s
59:	learn: 1.3650781	test: 1.4136224	best: 1.4136224 (59)	total: 39.9s	remaining: 2m 39s
60:	learn: 1.3638047	test: 1.4126622	best: 1.4126622 (60)	total: 40.4s	remaining: 2m 38s
61:	learn: 1.3630456	test: 1.4126089	best: 1.4126089 (61)	total: 41s	remaining: 2m 37s
62:	learn: 1.3608697	test: 1.4124399	best: 1.4124399 (62)	total: 41.8s	remaining: 2m 37s
63:	learn: 1.3597175	test: 1.4116908	best: 1.4116908 (63)	total: 42.5s	remaining: 2m 36s
64:	learn: 1.3574497	test: 1.4110871	best: 1.4110871 (64)	total: 43.3s	remaining: 2m 36s
65:	learn: 1.3574451	test: 1.4110879	best: 1.4110871 (64)	total: 43.5s	remaining: 2m 34s
66:	learn: 1.3566384	test: 1.4112055	best: 1.4110871 (64)	total: 44.2s	remaining: 2m 33s
67:	learn: 1.3559471	test: 1.4107546	best: 1.4107546 (67)	total: 44.9s	remaining: 2m 33s
68:	learn: 1.3552533	test: 1.4101751	best: 1.4101751 (68)	total: 45.5s	remaining: 2m 32s
69:	learn: 1.3547266	test: 1.4100181	best: 1.4100181 (69)	total: 46.3s	remaining: 2m 32s
70:	learn: 1.3540125	test: 1.4096517	best: 1.4096517 (70)	total: 47s	remaining: 2m 31s
71:	learn: 1.3524360	test: 1.4088358	best: 1.4088358 (71)	total: 47.7s	remaining: 2m 31s
72:	learn: 1.3508378	test: 1.4073397	best: 1.4073397 (72)	total: 48.4s	remaining: 2m 30s
73:	learn: 1.3497381	test: 1.4071513	best: 1.4071513 (73)	total: 49s	remaining: 2m 29s
74:	learn: 1.3492501	test: 1.4067402	best: 1.4067402 (74)	total: 49.7s	remaining: 2m 29s
75:	learn: 1.3477908	test: 1.4059586	best: 1.4059586 (75)	total: 50.4s	remaining: 2m 28s
76:	learn: 1.3469002	test: 1.4051378	best: 1.4051378 (76)	total: 51s	remaining: 2m 27s
77:	learn: 1.3455357	test: 1.4047369	best: 1.4047369 (77)	total: 51.7s	remaining: 2m 27s
78:	learn: 1.3455255	test: 1.4047415	best: 1.4047369 (77)	total: 51.9s	remaining: 2m 25s
79:	learn: 1.3449069	test: 1.4049594	best: 1.4047369 (77)	total: 52.4s	remaining: 2m 24s
80:	learn: 1.3436988	test: 1.4053334	best: 1.4047369 (77)	total: 53.1s	remaining: 2m 23s
81:	learn: 1.3428051	test: 1.4052698	best: 1.4047369 (77)	total: 53.8s	remaining: 2m 23s
82:	learn: 1.3407893	test: 1.4053560	best: 1.4047369 (77)	total: 54.5s	remaining: 2m 22s
83:	learn: 1.3390240	test: 1.4043292	best: 1.4043292 (83)	total: 55.2s	remaining: 2m 21s
84:	learn: 1.3388552	test: 1.4040769	best: 1.4040769 (84)	total: 55.4s	remaining: 2m 20s
85:	learn: 1.3381423	test: 1.4038661	best: 1.4038661 (85)	total: 55.9s	remaining: 2m 19s
86:	learn: 1.3366484	test: 1.4036887	best: 1.4036887 (86)	total: 56.7s	remaining: 2m 18s
87:	learn: 1.3366483	test: 1.4036899	best: 1.4036887 (86)	total: 56.8s	remaining: 2m 16s
88:	learn: 1.3358291	test: 1.4038883	best: 1.4036887 (86)	total: 57.4s	remaining: 2m 16s
89:	learn: 1.3340788	test: 1.4036920	best: 1.4036887 (86)	total: 58.1s	remaining: 2m 15s
90:	learn: 1.3319416	test: 1.4020761	best: 1.4020761 (90)	total: 58.8s	remaining: 2m 15s
91:	learn: 1.3297574	test: 1.4011461	best: 1.4011461 (91)	total: 59.5s	remaining: 2m 14s
92:	learn: 1.3284198	test: 1.4009310	best: 1.4009310 (92)	total: 1m	remaining: 2m 14s
93:	learn: 1.3275035	test: 1.3998811	best: 1.3998811 (93)	total: 1m	remaining: 2m 13s
94:	learn: 1.3272034	test: 1.3997356	best: 1.3997356 (94)	total: 1m 1s	remaining: 2m 13s
95:	learn: 1.3271418	test: 1.3997661	best: 1.3997356 (94)	total: 1m 1s	remaining: 2m 11s
96:	learn: 1.3264485	test: 1.3996646	best: 1.3996646 (96)	total: 1m 2s	remaining: 2m 10s
97:	learn: 1.3248316	test: 1.3990187	best: 1.3990187 (97)	total: 1m 3s	remaining: 2m 10s
98:	learn: 1.3230987	test: 1.3992439	best: 1.3990187 (97)	total: 1m 3s	remaining: 2m 9s
99:	learn: 1.3223032	test: 1.3991874	best: 1.3990187 (97)	total: 1m 4s	remaining: 2m 9s
100:	learn: 1.3212422	test: 1.3992063	best: 1.3990187 (97)	total: 1m 5s	remaining: 2m 8s
101:	learn: 1.3200145	test: 1.3989009	best: 1.3989009 (101)	total: 1m 6s	remaining: 2m 8s
102:	learn: 1.3184583	test: 1.3977608	best: 1.3977608 (102)	total: 1m 6s	remaining: 2m 7s
103:	learn: 1.3168662	test: 1.3978618	best: 1.3977608 (102)	total: 1m 7s	remaining: 2m 7s
104:	learn: 1.3162162	test: 1.3976164	best: 1.3976164 (104)	total: 1m 7s	remaining: 2m 6s
105:	learn: 1.3150337	test: 1.3982626	best: 1.3976164 (104)	total: 1m 8s	remaining: 2m 5s
106:	learn: 1.3135771	test: 1.3985307	best: 1.3976164 (104)	total: 1m 9s	remaining: 2m 5s
107:	learn: 1.3124007	test: 1.3981936	best: 1.3976164 (104)	total: 1m 9s	remaining: 2m 4s
108:	learn: 1.3117570	test: 1.3978787	best: 1.3976164 (104)	total: 1m 10s	remaining: 2m 3s
109:	learn: 1.3109296	test: 1.3980551	best: 1.3976164 (104)	total: 1m 11s	remaining: 2m 3s
110:	learn: 1.3102710	test: 1.3978310	best: 1.3976164 (104)	total: 1m 12s	remaining: 2m 2s
111:	learn: 1.3094410	test: 1.3977015	best: 1.3976164 (104)	total: 1m 12s	remaining: 2m 2s
112:	learn: 1.3078882	test: 1.3981511	best: 1.3976164 (104)	total: 1m 13s	remaining: 2m 1s
113:	learn: 1.3069006	test: 1.3980160	best: 1.3976164 (104)	total: 1m 14s	remaining: 2m 1s
114:	learn: 1.3057384	test: 1.3978930	best: 1.3976164 (104)	total: 1m 15s	remaining: 2m
115:	learn: 1.3047468	test: 1.3978327	best: 1.3976164 (104)	total: 1m 15s	remaining: 2m
116:	learn: 1.3037240	test: 1.3978238	best: 1.3976164 (104)	total: 1m 16s	remaining: 1m 59s
117:	learn: 1.3015877	test: 1.3957570	best: 1.3957570 (117)	total: 1m 16s	remaining: 1m 58s
118:	learn: 1.3013422	test: 1.3957458	best: 1.3957458 (118)	total: 1m 17s	remaining: 1m 58s
119:	learn: 1.3008728	test: 1.3956970	best: 1.3956970 (119)	total: 1m 18s	remaining: 1m 57s
120:	learn: 1.2996170	test: 1.3946196	best: 1.3946196 (120)	total: 1m 18s	remaining: 1m 56s
121:	learn: 1.2987765	test: 1.3947528	best: 1.3946196 (120)	total: 1m 19s	remaining: 1m 56s
122:	learn: 1.2969779	test: 1.3943600	best: 1.3943600 (122)	total: 1m 20s	remaining: 1m 55s
123:	learn: 1.2961624	test: 1.3939913	best: 1.3939913 (123)	total: 1m 21s	remaining: 1m 55s
124:	learn: 1.2952834	test: 1.3935002	best: 1.3935002 (124)	total: 1m 21s	remaining: 1m 54s
125:	learn: 1.2939151	test: 1.3931410	best: 1.3931410 (125)	total: 1m 22s	remaining: 1m 53s
126:	learn: 1.2924283	test: 1.3926220	best: 1.3926220 (126)	total: 1m 23s	remaining: 1m 53s
127:	learn: 1.2918939	test: 1.3925731	best: 1.3925731 (127)	total: 1m 23s	remaining: 1m 52s
128:	learn: 1.2907131	test: 1.3921930	best: 1.3921930 (128)	total: 1m 24s	remaining: 1m 52s
129:	learn: 1.2895577	test: 1.3920127	best: 1.3920127 (129)	total: 1m 25s	remaining: 1m 51s
130:	learn: 1.2885391	test: 1.3915296	best: 1.3915296 (130)	total: 1m 25s	remaining: 1m 50s
131:	learn: 1.2867820	test: 1.3903569	best: 1.3903569 (131)	total: 1m 26s	remaining: 1m 50s
132:	learn: 1.2856059	test: 1.3898509	best: 1.3898509 (132)	total: 1m 27s	remaining: 1m 49s
133:	learn: 1.2836645	test: 1.3905187	best: 1.3898509 (132)	total: 1m 27s	remaining: 1m 48s
134:	learn: 1.2828034	test: 1.3904404	best: 1.3898509 (132)	total: 1m 28s	remaining: 1m 48s
135:	learn: 1.2821041	test: 1.3906074	best: 1.3898509 (132)	total: 1m 29s	remaining: 1m 47s
136:	learn: 1.2810334	test: 1.3902441	best: 1.3898509 (132)	total: 1m 30s	remaining: 1m 47s
137:	learn: 1.2804195	test: 1.3902025	best: 1.3898509 (132)	total: 1m 31s	remaining: 1m 47s
138:	learn: 1.2791094	test: 1.3901640	best: 1.3898509 (132)	total: 1m 32s	remaining: 1m 46s
139:	learn: 1.2780223	test: 1.3895484	best: 1.3895484 (139)	total: 1m 33s	remaining: 1m 46s
140:	learn: 1.2771641	test: 1.3889791	best: 1.3889791 (140)	total: 1m 33s	remaining: 1m 45s
141:	learn: 1.2762389	test: 1.3887367	best: 1.3887367 (141)	total: 1m 34s	remaining: 1m 45s
142:	learn: 1.2754889	test: 1.3885056	best: 1.3885056 (142)	total: 1m 35s	remaining: 1m 44s
143:	learn: 1.2745626	test: 1.3886041	best: 1.3885056 (142)	total: 1m 36s	remaining: 1m 44s
144:	learn: 1.2740183	test: 1.3885809	best: 1.3885056 (142)	total: 1m 37s	remaining: 1m 43s
145:	learn: 1.2732063	test: 1.3886632	best: 1.3885056 (142)	total: 1m 38s	remaining: 1m 43s
146:	learn: 1.2723725	test: 1.3882554	best: 1.3882554 (146)	total: 1m 39s	remaining: 1m 43s
147:	learn: 1.2717963	test: 1.3884890	best: 1.3882554 (146)	total: 1m 40s	remaining: 1m 42s
148:	learn: 1.2701079	test: 1.3883370	best: 1.3882554 (146)	total: 1m 41s	remaining: 1m 42s
149:	learn: 1.2690052	test: 1.3881569	best: 1.3881569 (149)	total: 1m 42s	remaining: 1m 42s
150:	learn: 1.2683959	test: 1.3881644	best: 1.3881569 (149)	total: 1m 42s	remaining: 1m 41s
151:	learn: 1.2676019	test: 1.3883610	best: 1.3881569 (149)	total: 1m 43s	remaining: 1m 41s
152:	learn: 1.2665092	test: 1.3882489	best: 1.3881569 (149)	total: 1m 44s	remaining: 1m 40s
153:	learn: 1.2654836	test: 1.3884154	best: 1.3881569 (149)	total: 1m 45s	remaining: 1m 40s
154:	learn: 1.2648973	test: 1.3883778	best: 1.3881569 (149)	total: 1m 46s	remaining: 1m 39s
155:	learn: 1.2643022	test: 1.3881716	best: 1.3881569 (149)	total: 1m 47s	remaining: 1m 39s
156:	learn: 1.2631179	test: 1.3882488	best: 1.3881569 (149)	total: 1m 48s	remaining: 1m 38s
157:	learn: 1.2621697	test: 1.3883113	best: 1.3881569 (149)	total: 1m 49s	remaining: 1m 38s
158:	learn: 1.2611599	test: 1.3876680	best: 1.3876680 (158)	total: 1m 49s	remaining: 1m 37s
159:	learn: 1.2600370	test: 1.3877842	best: 1.3876680 (158)	total: 1m 50s	remaining: 1m 37s
160:	learn: 1.2585472	test: 1.3879116	best: 1.3876680 (158)	total: 1m 51s	remaining: 1m 36s
161:	learn: 1.2576745	test: 1.3881603	best: 1.3876680 (158)	total: 1m 52s	remaining: 1m 36s
162:	learn: 1.2571885	test: 1.3883588	best: 1.3876680 (158)	total: 1m 53s	remaining: 1m 35s
163:	learn: 1.2560047	test: 1.3882138	best: 1.3876680 (158)	total: 1m 54s	remaining: 1m 35s
164:	learn: 1.2544278	test: 1.3876350	best: 1.3876350 (164)	total: 1m 55s	remaining: 1m 34s
165:	learn: 1.2538702	test: 1.3875280	best: 1.3875280 (165)	total: 1m 56s	remaining: 1m 33s
166:	learn: 1.2530573	test: 1.3873979	best: 1.3873979 (166)	total: 1m 57s	remaining: 1m 33s
167:	learn: 1.2524176	test: 1.3872413	best: 1.3872413 (167)	total: 1m 58s	remaining: 1m 32s
168:	learn: 1.2514754	test: 1.3872504	best: 1.3872413 (167)	total: 1m 58s	remaining: 1m 32s
169:	learn: 1.2503054	test: 1.3866602	best: 1.3866602 (169)	total: 1m 59s	remaining: 1m 31s
170:	learn: 1.2495008	test: 1.3868086	best: 1.3866602 (169)	total: 2m	remaining: 1m 30s
171:	learn: 1.2485339	test: 1.3866413	best: 1.3866413 (171)	total: 2m 1s	remaining: 1m 30s
172:	learn: 1.2478837	test: 1.3865358	best: 1.3865358 (172)	total: 2m 2s	remaining: 1m 29s
173:	learn: 1.2473826	test: 1.3862923	best: 1.3862923 (173)	total: 2m 3s	remaining: 1m 29s
174:	learn: 1.2468924	test: 1.3862146	best: 1.3862146 (174)	total: 2m 4s	remaining: 1m 28s
175:	learn: 1.2460680	test: 1.3862300	best: 1.3862146 (174)	total: 2m 5s	remaining: 1m 28s
176:	learn: 1.2453131	test: 1.3862506	best: 1.3862146 (174)	total: 2m 6s	remaining: 1m 27s
177:	learn: 1.2445401	test: 1.3865943	best: 1.3862146 (174)	total: 2m 7s	remaining: 1m 27s
178:	learn: 1.2440321	test: 1.3863859	best: 1.3862146 (174)	total: 2m 8s	remaining: 1m 26s
179:	learn: 1.2432935	test: 1.3861723	best: 1.3861723 (179)	total: 2m 9s	remaining: 1m 26s
180:	learn: 1.2430114	test: 1.3861432	best: 1.3861432 (180)	total: 2m 10s	remaining: 1m 25s
181:	learn: 1.2420599	test: 1.3859249	best: 1.3859249 (181)	total: 2m 11s	remaining: 1m 25s
182:	learn: 1.2408167	test: 1.3852270	best: 1.3852270 (182)	total: 2m 12s	remaining: 1m 24s
183:	learn: 1.2404945	test: 1.3850965	best: 1.3850965 (183)	total: 2m 13s	remaining: 1m 23s
184:	learn: 1.2392698	test: 1.3850736	best: 1.3850736 (184)	total: 2m 14s	remaining: 1m 23s
185:	learn: 1.2383795	test: 1.3854794	best: 1.3850736 (184)	total: 2m 14s	remaining: 1m 22s
186:	learn: 1.2379900	test: 1.3853705	best: 1.3850736 (184)	total: 2m 15s	remaining: 1m 22s
187:	learn: 1.2371970	test: 1.3854858	best: 1.3850736 (184)	total: 2m 16s	remaining: 1m 21s
188:	learn: 1.2358655	test: 1.3853502	best: 1.3850736 (184)	total: 2m 17s	remaining: 1m 20s
189:	learn: 1.2352266	test: 1.3853707	best: 1.3850736 (184)	total: 2m 18s	remaining: 1m 20s
190:	learn: 1.2339247	test: 1.3853719	best: 1.3850736 (184)	total: 2m 19s	remaining: 1m 19s
191:	learn: 1.2333202	test: 1.3851562	best: 1.3850736 (184)	total: 2m 20s	remaining: 1m 18s
192:	learn: 1.2324290	test: 1.3857802	best: 1.3850736 (184)	total: 2m 21s	remaining: 1m 18s
193:	learn: 1.2312958	test: 1.3859140	best: 1.3850736 (184)	total: 2m 22s	remaining: 1m 17s
194:	learn: 1.2307933	test: 1.3856385	best: 1.3850736 (184)	total: 2m 23s	remaining: 1m 17s
195:	learn: 1.2299989	test: 1.3855515	best: 1.3850736 (184)	total: 2m 24s	remaining: 1m 16s
196:	learn: 1.2294107	test: 1.3855390	best: 1.3850736 (184)	total: 2m 25s	remaining: 1m 16s
197:	learn: 1.2286640	test: 1.3853018	best: 1.3850736 (184)	total: 2m 26s	remaining: 1m 15s
198:	learn: 1.2276286	test: 1.3852473	best: 1.3850736 (184)	total: 2m 27s	remaining: 1m 14s
199:	learn: 1.2269611	test: 1.3850390	best: 1.3850390 (199)	total: 2m 28s	remaining: 1m 14s
200:	learn: 1.2266796	test: 1.3850150	best: 1.3850150 (200)	total: 2m 29s	remaining: 1m 13s
201:	learn: 1.2260164	test: 1.3848834	best: 1.3848834 (201)	total: 2m 30s	remaining: 1m 13s
202:	learn: 1.2251362	test: 1.3847166	best: 1.3847166 (202)	total: 2m 31s	remaining: 1m 12s
203:	learn: 1.2246477	test: 1.3846213	best: 1.3846213 (203)	total: 2m 32s	remaining: 1m 11s
204:	learn: 1.2230532	test: 1.3852342	best: 1.3846213 (203)	total: 2m 33s	remaining: 1m 11s
205:	learn: 1.2219346	test: 1.3853461	best: 1.3846213 (203)	total: 2m 34s	remaining: 1m 10s
206:	learn: 1.2212544	test: 1.3855037	best: 1.3846213 (203)	total: 2m 35s	remaining: 1m 9s
207:	learn: 1.2203861	test: 1.3855558	best: 1.3846213 (203)	total: 2m 36s	remaining: 1m 9s
208:	learn: 1.2193977	test: 1.3857423	best: 1.3846213 (203)	total: 2m 37s	remaining: 1m 8s
209:	learn: 1.2189023	test: 1.3859570	best: 1.3846213 (203)	total: 2m 38s	remaining: 1m 8s
210:	learn: 1.2184271	test: 1.3856809	best: 1.3846213 (203)	total: 2m 40s	remaining: 1m 7s
211:	learn: 1.2172174	test: 1.3862277	best: 1.3846213 (203)	total: 2m 41s	remaining: 1m 6s
212:	learn: 1.2167604	test: 1.3862605	best: 1.3846213 (203)	total: 2m 42s	remaining: 1m 6s
213:	learn: 1.2153590	test: 1.3863644	best: 1.3846213 (203)	total: 2m 43s	remaining: 1m 5s
214:	learn: 1.2148554	test: 1.3863884	best: 1.3846213 (203)	total: 2m 44s	remaining: 1m 4s
215:	learn: 1.2135343	test: 1.3866171	best: 1.3846213 (203)	total: 2m 45s	remaining: 1m 4s
216:	learn: 1.2129729	test: 1.3862771	best: 1.3846213 (203)	total: 2m 46s	remaining: 1m 3s
217:	learn: 1.2118150	test: 1.3862698	best: 1.3846213 (203)	total: 2m 47s	remaining: 1m 2s
218:	learn: 1.2115133	test: 1.3863536	best: 1.3846213 (203)	total: 2m 48s	remaining: 1m 2s
219:	learn: 1.2112014	test: 1.3865411	best: 1.3846213 (203)	total: 2m 49s	remaining: 1m 1s
220:	learn: 1.2102358	test: 1.3868165	best: 1.3846213 (203)	total: 2m 50s	remaining: 1m
221:	learn: 1.2099620	test: 1.3868519	best: 1.3846213 (203)	total: 2m 51s	remaining: 1m

2026/02/21 20:25:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

- Cat1 model scores-

    - f1-score: 0.4472.
    - recall score: 0.4245.
    - precision score: 0.4972.

In [12]:
# Starting the MLflow run
with mlflow.start_run(run_name='CatBoostClassifier_2'):

    # Initializing the CatBoostClassifier model
    cat2 = CatBoostClassifier(iterations=800,
                              depth=8,
                              learning_rate=0.01,
                              loss_function='MultiClass',
                              class_weights=class_weights,
                              random_seed=42)
    
    # Fitting the model on the training data
    cat2.fit(x_train, y_train, cat_features=cat_features, eval_set=(x_test, y_test), verbose=1)
    
    # Predicting the Visit Mode on the test data
    y_pred = cat2.predict(x_test)
    
    # Evaluating the model performance
    f1 = f1_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    precision = precision_score(y_test, y_pred, average='weighted')
    
    # Logging the parameters and metrics to MLflow
    mlflow.log_param('model_name', 'CatBoostClassifier')
    mlflow.log_param('iterations', 800)
    mlflow.log_param('depth', 6)
    mlflow.log_param('learning_rate', 0.3)
    mlflow.log_metric('f1_score', f1)
    mlflow.log_metric('recall_score', recall)
    mlflow.log_metric('precision_score', precision)

    # Logging the model to MLflow
    mlflow.catboost.log_model(cat2, 'cat2')

0:	learn: 1.6064711	test: 1.6068985	best: 1.6068985 (0)	total: 3.61s	remaining: 48m 4s
1:	learn: 1.6034189	test: 1.6042454	best: 1.6042454 (1)	total: 6.55s	remaining: 43m 35s
2:	learn: 1.6007122	test: 1.6017850	best: 1.6017850 (2)	total: 9.25s	remaining: 40m 57s
3:	learn: 1.5982033	test: 1.5996053	best: 1.5996053 (3)	total: 11.6s	remaining: 38m 32s
4:	learn: 1.5955774	test: 1.5972107	best: 1.5972107 (4)	total: 14.2s	remaining: 37m 33s
5:	learn: 1.5932098	test: 1.5950552	best: 1.5950552 (5)	total: 16.7s	remaining: 36m 55s
6:	learn: 1.5909700	test: 1.5930364	best: 1.5930364 (6)	total: 19s	remaining: 35m 49s
7:	learn: 1.5885698	test: 1.5909615	best: 1.5909615 (7)	total: 21.1s	remaining: 34m 51s
8:	learn: 1.5859398	test: 1.5888094	best: 1.5888094 (8)	total: 23.1s	remaining: 33m 53s
9:	learn: 1.5835356	test: 1.5866947	best: 1.5866947 (9)	total: 25.2s	remaining: 33m 8s
10:	learn: 1.5816495	test: 1.5848845	best: 1.5848845 (10)	total: 27.5s	remaining: 32m 53s
11:	learn: 1.5792603	test: 1.5829083	best: 1.5829083 (11)	total: 29.7s	remaining: 32m 31s
12:	learn: 1.5767267	test: 1.5808489	best: 1.5808489 (12)	total: 31.7s	remaining: 32m 1s
13:	learn: 1.5747241	test: 1.5790616	best: 1.5790616 (13)	total: 34.1s	remaining: 31m 52s
14:	learn: 1.5721754	test: 1.5770022	best: 1.5770022 (14)	total: 36.3s	remaining: 31m 37s
15:	learn: 1.5700973	test: 1.5753055	best: 1.5753055 (15)	total: 38.5s	remaining: 31m 26s
16:	learn: 1.5678193	test: 1.5734600	best: 1.5734600 (16)	total: 40.8s	remaining: 31m 19s
17:	learn: 1.5661090	test: 1.5719104	best: 1.5719104 (17)	total: 43.1s	remaining: 31m 13s
18:	learn: 1.5641217	test: 1.5700876	best: 1.5700876 (18)	total: 45.3s	remaining: 31m 3s
19:	learn: 1.5624508	test: 1.5685855	best: 1.5685855 (19)	total: 47.6s	remaining: 30m 55s
20:	learn: 1.5607640	test: 1.5671574	best: 1.5671574 (20)	total: 49.9s	remaining: 30m 50s
21:	learn: 1.5589877	test: 1.5655664	best: 1.5655664 (21)	total: 52.3s	remaining: 30m 48s
22:	learn: 1.5570923	test: 1.5639702	best: 1.5639702 (22)	total: 54.9s	remaining: 30m 54s
23:	learn: 1.5555216	test: 1.5625502	best: 1.5625502 (23)	total: 57.3s	remaining: 30m 52s
24:	learn: 1.5536002	test: 1.5611017	best: 1.5611017 (24)	total: 59.6s	remaining: 30m 48s
25:	learn: 1.5518969	test: 1.5596389	best: 1.5596389 (25)	total: 1m 1s	remaining: 30m 36s
26:	learn: 1.5499271	test: 1.5580737	best: 1.5580737 (26)	total: 1m 4s	remaining: 30m 32s
27:	learn: 1.5480735	test: 1.5566310	best: 1.5566310 (27)	total: 1m 6s	remaining: 30m 31s
28:	learn: 1.5466244	test: 1.5553460	best: 1.5553460 (28)	total: 1m 8s	remaining: 30m 18s
29:	learn: 1.5446462	test: 1.5537647	best: 1.5537647 (29)	total: 1m 10s	remaining: 30m 17s
30:	learn: 1.5431805	test: 1.5525238	best: 1.5525238 (30)	total: 1m 13s	remaining: 30m 13s
31:	learn: 1.5417499	test: 1.5512785	best: 1.5512785 (31)	total: 1m 15s	remaining: 30m 9s
32:	learn: 1.5401683	test: 1.5499718	best: 1.5499718 (32)	total: 1m 17s	remaining: 30m 12s
33:	learn: 1.5381772	test: 1.5484351	best: 1.5484351 (33)	total: 1m 20s	remaining: 30m 15s
34:	learn: 1.5366345	test: 1.5471090	best: 1.5471090 (34)	total: 1m 23s	remaining: 30m 26s
35:	learn: 1.5357732	test: 1.5463414	best: 1.5463414 (35)	total: 1m 24s	remaining: 29m 57s
36:	learn: 1.5338325	test: 1.5448090	best: 1.5448090 (36)	total: 1m 27s	remaining: 30m
37:	learn: 1.5324805	test: 1.5437209	best: 1.5437209 (37)	total: 1m 29s	remaining: 30m 1s
38:	learn: 1.5309250	test: 1.5424088	best: 1.5424088 (38)	total: 1m 31s	remaining: 29m 53s
39:	learn: 1.5294886	test: 1.5412310	best: 1.5412310 (39)	total: 1m 33s	remaining: 29m 45s
40:	learn: 1.5282008	test: 1.5399275	best: 1.5399275 (40)	total: 1m 34s	remaining: 29m 17s
41:	learn: 1.5266978	test: 1.5387784	best: 1.5387784 (41)	total: 1m 37s	remaining: 29m 11s
42:	learn: 1.5252789	test: 1.5376110	best: 1.5376110 (42)	total: 1m 39s	remaining: 29m 6s
43:	learn: 1.5234917	test: 1.5361390	best: 1.5361390 (43)	total: 1m 41s	remaining: 29m 1s
44:	learn: 1.5220705	test: 1.5350768	best: 1.5350768 (44)	total: 1m 43s	remaining: 28m 56s
45:	learn: 1.5208214	test: 1.5341428	best: 1.5341428 (45)	total: 1m 45s	remaining: 28m 56s
46:	learn: 1.5195919	test: 1.5332308	best: 1.5332308 (46)	total: 1m 48s	remaining: 28m 51s
47:	learn: 1.5184250	test: 1.5323188	best: 1.5323188 (47)	total: 1m 50s	remaining: 28m 58s
48:	learn: 1.5170498	test: 1.5313886	best: 1.5313886 (48)	total: 1m 53s	remaining: 28m 55s
49:	learn: 1.5158275	test: 1.5304359	best: 1.5304359 (49)	total: 1m 55s	remaining: 28m 49s
50:	learn: 1.5147447	test: 1.5295918	best: 1.5295918 (50)	total: 1m 57s	remaining: 28m 48s
51:	learn: 1.5133837	test: 1.5286182	best: 1.5286182 (51)	total: 2m	remaining: 28m 48s
52:	learn: 1.5119544	test: 1.5277215	best: 1.5277215 (52)	total: 2m 2s	remaining: 28m 45s
53:	learn: 1.5104633	test: 1.5268201	best: 1.5268201 (53)	total: 2m 4s	remaining: 28m 45s
54:	learn: 1.5092875	test: 1.5259319	best: 1.5259319 (54)	total: 2m 7s	remaining: 28m 42s
55:	learn: 1.5080894	test: 1.5251163	best: 1.5251163 (55)	total: 2m 9s	remaining: 28m 41s
56:	learn: 1.5071896	test: 1.5245284	best: 1.5245284 (56)	total: 2m 11s	remaining: 28m 37s
57:	learn: 1.5058180	test: 1.5235673	best: 1.5235673 (57)	total: 2m 13s	remaining: 28m 33s
58:	learn: 1.5045970	test: 1.5227386	best: 1.5227386 (58)	total: 2m 16s	remaining: 28m 28s
59:	learn: 1.5035670	test: 1.5219066	best: 1.5219066 (59)	total: 2m 18s	remaining: 28m 28s
60:	learn: 1.5023761	test: 1.5210646	best: 1.5210646 (60)	total: 2m 20s	remaining: 28m 27s
61:	learn: 1.5013133	test: 1.5202190	best: 1.5202190 (61)	total: 2m 23s	remaining: 28m 27s
62:	learn: 1.5000544	test: 1.5194122	best: 1.5194122 (62)	total: 2m 25s	remaining: 28m 26s
63:	learn: 1.4987258	test: 1.5185006	best: 1.5185006 (63)	total: 2m 28s	remaining: 28m 26s
64:	learn: 1.4978329	test: 1.5177490	best: 1.5177490 (64)	total: 2m 31s	remaining: 28m 28s
65:	learn: 1.4966650	test: 1.5169035	best: 1.5169035 (65)	total: 2m 33s	remaining: 28m 25s
66:	learn: 1.4953987	test: 1.5161256	best: 1.5161256 (66)	total: 2m 36s	remaining: 28m 27s
67:	learn: 1.4942629	test: 1.5153370	best: 1.5153370 (67)	total: 2m 38s	remaining: 28m 28s
68:	learn: 1.4932639	test: 1.5146603	best: 1.5146603 (68)	total: 2m 41s	remaining: 28m 30s
69:	learn: 1.4920370	test: 1.5139005	best: 1.5139005 (69)	total: 2m 44s	remaining: 28m 33s
70:	learn: 1.4908960	test: 1.5131251	best: 1.5131251 (70)	total: 2m 47s	remaining: 28m 37s
71:	learn: 1.4898379	test: 1.5124015	best: 1.5124015 (71)	total: 2m 50s	remaining: 28m 38s
72:	learn: 1.4887790	test: 1.5118674	best: 1.5118674 (72)	total: 2m 52s	remaining: 28m 34s
73:	learn: 1.4876259	test: 1.5111092	best: 1.5111092 (73)	total: 2m 54s	remaining: 28m 31s
74:	learn: 1.4869306	test: 1.5106374	best: 1.5106374 (74)	total: 2m 56s	remaining: 28m 25s
75:	learn: 1.4859645	test: 1.5100703	best: 1.5100703 (75)	total: 2m 58s	remaining: 28m 21s
76:	learn: 1.4848242	test: 1.5093835	best: 1.5093835 (76)	total: 3m	remaining: 28m 17s
77:	learn: 1.4836704	test: 1.5087069	best: 1.5087069 (77)	total: 3m 3s	remaining: 28m 14s
78:	learn: 1.4825503	test: 1.5079971	best: 1.5079971 (78)	total: 3m 5s	remaining: 28m 12s
79:	learn: 1.4815986	test: 1.5074423	best: 1.5074423 (79)	total: 3m 7s	remaining: 28m 11s
80:	learn: 1.4807490	test: 1.5067695	best: 1.5067695 (80)	total: 3m 9s	remaining: 28m 4s
81:	learn: 1.4799091	test: 1.5061657	best: 1.5061657 (81)	total: 3m 12s	remaining: 28m 1s
82:	learn: 1.4790691	test: 1.5056076	best: 1.5056076 (82)	total: 3m 14s	remaining: 27m 59s
83:	learn: 1.4783330	test: 1.5050349	best: 1.5050349 (83)	total: 3m 16s	remaining: 27m 56s
84:	learn: 1.4772907	test: 1.5044347	best: 1.5044347 (84)	total: 3m 18s	remaining: 27m 51s
85:	learn: 1.4764538	test: 1.5038451	best: 1.5038451 (85)	total: 3m 20s	remaining: 27m 47s
86:	learn: 1.4755409	test: 1.5032595	best: 1.5032595 (86)	total: 3m 23s	remaining: 27m 45s
87:	learn: 1.4747646	test: 1.5027401	best: 1.5027401 (87)	total: 3m 25s	remaining: 27m 43s
88:	learn: 1.4740604	test: 1.5022405	best: 1.5022405 (88)	total: 3m 27s	remaining: 27m 38s
89:	learn: 1.4733932	test: 1.5018383	best: 1.5018383 (89)	total: 3m 29s	remaining: 27m 34s
90:	learn: 1.4721603	test: 1.5011298	best: 1.5011298 (90)	total: 3m 32s	remaining: 27m 32s
91:	learn: 1.4713424	test: 1.5005433	best: 1.5005433 (91)	total: 3m 33s	remaining: 27m 26s
92:	learn: 1.4704623	test: 1.5001001	best: 1.5001001 (92)	total: 3m 35s	remaining: 27m 21s
93:	learn: 1.4692999	test: 1.4994366	best: 1.4994366 (93)	total: 3m 38s	remaining: 27m 20s
94:	learn: 1.4685754	test: 1.4989356	best: 1.4989356 (94)	total: 3m 40s	remaining: 27m 15s
95:	learn: 1.4676508	test: 1.4985134	best: 1.4985134 (95)	total: 3m 42s	remaining: 27m 13s
96:	learn: 1.4668147	test: 1.4979353	best: 1.4979353 (96)	total: 3m 45s	remaining: 27m 12s
97:	learn: 1.4658392	test: 1.4974165	best: 1.4974165 (97)	total: 3m 47s	remaining: 27m 10s
98:	learn: 1.4650342	test: 1.4969006	best: 1.4969006 (98)	total: 3m 50s	remaining: 27m 8s
99:	learn: 1.4642998	test: 1.4964541	best: 1.4964541 (99)	total: 3m 52s	remaining: 27m 8s
100:	learn: 1.4635120	test: 1.4959859	best: 1.4959859 (100)	total: 3m 55s	remaining: 27m 6s
101:	learn: 1.4625044	test: 1.4955758	best: 1.4955758 (101)	total: 3m 57s	remaining: 27m 5s
102:	learn: 1.4617257	test: 1.4952225	best: 1.4952225 (102)	total: 3m 59s	remaining: 27m 3s
103:	learn: 1.4608411	test: 1.4947244	best: 1.4947244 (103)	total: 4m 2s	remaining: 27m 1s
104:	learn: 1.4603990	test: 1.4943872	best: 1.4943872 (104)	total: 4m 4s	remaining: 26m 58s
105:	learn: 1.4598360	test: 1.4940014	best: 1.4940014 (105)	total: 4m 6s	remaining: 26m 55s
106:	learn: 1.4589347	test: 1.4935718	best: 1.4935718 (106)	total: 4m 9s	remaining: 26m 53s
107:	learn: 1.4583765	test: 1.4932460	best: 1.4932460 (107)	total: 4m 11s	remaining: 26m 50s
108:	learn: 1.4576427	test: 1.4929321	best: 1.4929321 (108)	total: 4m 13s	remaining: 26m 49s
109:	learn: 1.4569427	test: 1.4925808	best: 1.4925808 (109)	total: 4m 16s	remaining: 26m 47s
110:	learn: 1.4562656	test: 1.4922160	best: 1.4922160 (110)	total: 4m 18s	remaining: 26m 44s
111:	learn: 1.4555959	test: 1.4917881	best: 1.4917881 (111)	total: 4m 20s	remaining: 26m 41s
112:	learn: 1.4548845	test: 1.4913880	best: 1.4913880 (112)	total: 4m 22s	remaining: 26m 37s
113:	learn: 1.4541483	test: 1.4910653	best: 1.4910653 (113)	total: 4m 24s	remaining: 26m 33s
114:	learn: 1.4533849	test: 1.4906065	best: 1.4906065 (114)	total: 4m 27s	remaining: 26m 31s
115:	learn: 1.4526595	test: 1.4902791	best: 1.4902791 (115)	total: 4m 29s	remaining: 26m 29s
116:	learn: 1.4517169	test: 1.4898779	best: 1.4898779 (116)	total: 4m 32s	remaining: 26m 27s
117:	learn: 1.4510357	test: 1.4895767	best: 1.4895767 (117)	total: 4m 33s	remaining: 26m 22s
118:	learn: 1.4505357	test: 1.4894329	best: 1.4894329 (118)	total: 4m 36s	remaining: 26m 19s
119:	learn: 1.4499199	test: 1.4890715	best: 1.4890715 (119)	total: 4m 38s	remaining: 26m 17s
120:	learn: 1.4489216	test: 1.4886297	best: 1.4886297 (120)	total: 4m 40s	remaining: 26m 16s
121:	learn: 1.4482833	test: 1.4882151	best: 1.4882151 (121)	total: 4m 43s	remaining: 26m 12s
122:	learn: 1.4475407	test: 1.4876473	best: 1.4876473 (122)	total: 4m 44s	remaining: 26m 8s
123:	learn: 1.4470638	test: 1.4873519	best: 1.4873519 (123)	total: 4m 47s	remaining: 26m 6s
124:	learn: 1.4462067	test: 1.4870410	best: 1.4870410 (124)	total: 4m 50s	remaining: 26m 7s
125:	learn: 1.4453427	test: 1.4866299	best: 1.4866299 (125)	total: 4m 52s	remaining: 26m 4s
126:	learn: 1.4445617	test: 1.4861347	best: 1.4861347 (126)	total: 4m 54s	remaining: 26m 2s
127:	learn: 1.4437303	test: 1.4856867	best: 1.4856867 (127)	total: 4m 57s	remaining: 26m 1s
128:	learn: 1.4429577	test: 1.4851521	best: 1.4851521 (128)	total: 4m 59s	remaining: 25m 57s
129:	learn: 1.4424437	test: 1.4849004	best: 1.4849004 (129)	total: 5m 1s	remaining: 25m 53s
130:	learn: 1.4419498	test: 1.4847124	best: 1.4847124 (130)	total: 5m 3s	remaining: 25m 52s
131:	learn: 1.4412141	test: 1.4843162	best: 1.4843162 (131)	total: 5m 6s	remaining: 25m 49s
132:	learn: 1.4402736	test: 1.4837699	best: 1.4837699 (132)	total: 5m 8s	remaining: 25m 47s
133:	learn: 1.4396770	test: 1.4833589	best: 1.4833589 (133)	total: 5m 10s	remaining: 25m 42s
134:	learn: 1.4391119	test: 1.4830732	best: 1.4830732 (134)	total: 5m 12s	remaining: 25m 39s
135:	learn: 1.4386991	test: 1.4828448	best: 1.4828448 (135)	total: 5m 14s	remaining: 25m 37s
136:	learn: 1.4381275	test: 1.4825028	best: 1.4825028 (136)	total: 5m 17s	remaining: 25m 35s
137:	learn: 1.4375903	test: 1.4821576	best: 1.4821576 (137)	total: 5m 19s	remaining: 25m 30s
138:	learn: 1.4369169	test: 1.4815631	best: 1.4815631 (138)	total: 5m 21s	remaining: 25m 27s
139:	learn: 1.4360469	test: 1.4808976	best: 1.4808976 (139)	total: 5m 23s	remaining: 25m 24s
140:	learn: 1.4352186	test: 1.4804879	best: 1.4804879 (140)	total: 5m 25s	remaining: 25m 20s
141:	learn: 1.4344215	test: 1.4801664	best: 1.4801664 (141)	total: 5m 27s	remaining: 25m 18s
142:	learn: 1.4340274	test: 1.4799007	best: 1.4799007 (142)	total: 5m 29s	remaining: 25m 16s
143:	learn: 1.4334313	test: 1.4796990	best: 1.4796990 (143)	total: 5m 32s	remaining: 25m 12s
144:	learn: 1.4331957	test: 1.4794105	best: 1.4794105 (144)	total: 5m 32s	remaining: 25m 2s
145:	learn: 1.4325884	test: 1.4790390	best: 1.4790390 (145)	total: 5m 34s	remaining: 24m 59s
146:	learn: 1.4318070	test: 1.4785866	best: 1.4785866 (146)	total: 5m 36s	remaining: 24m 55s
147:	learn: 1.4312601	test: 1.4782311	best: 1.4782311 (147)	total: 5m 38s	remaining: 24m 52s
148:	learn: 1.4307357	test: 1.4779411	best: 1.4779411 (148)	total: 5m 40s	remaining: 24m 49s
149:	learn: 1.4298330	test: 1.4773904	best: 1.4773904 (149)	total: 5m 42s	remaining: 24m 45s
150:	learn: 1.4291829	test: 1.4770443	best: 1.4770443 (150)	total: 5m 44s	remaining: 24m 42s
151:	learn: 1.4287123	test: 1.4768364	best: 1.4768364 (151)	total: 5m 47s	remaining: 24m 40s
152:	learn: 1.4279977	test: 1.4764806	best: 1.4764806 (152)	total: 5m 49s	remaining: 24m 36s
153:	learn: 1.4273416	test: 1.4759427	best: 1.4759427 (153)	total: 5m 51s	remaining: 24m 32s
154:	learn: 1.4268487	test: 1.4756710	best: 1.4756710 (154)	total: 5m 53s	remaining: 24m 30s
155:	learn: 1.4262577	test: 1.4752391	best: 1.4752391 (155)	total: 5m 55s	remaining: 24m 26s
156:	learn: 1.4257092	test: 1.4749980	best: 1.4749980 (156)	total: 5m 57s	remaining: 24m 22s
157:	learn: 1.4250289	test: 1.4745630	best: 1.4745630 (157)	total: 5m 59s	remaining: 24m 19s
158:	learn: 1.4245482	test: 1.4743797	best: 1.4743797 (158)	total: 6m 1s	remaining: 24m 17s
159:	learn: 1.4240767	test: 1.4740991	best: 1.4740991 (159)	total: 6m 3s	remaining: 24m 13s
160:	learn: 1.4235071	test: 1.4739653	best: 1.4739653 (160)	total: 6m 5s	remaining: 24m 11s
161:	learn: 1.4228936	test: 1.4735439	best: 1.4735439 (161)	total: 6m 7s	remaining: 24m 6s
162:	learn: 1.4223429	test: 1.4731597	best: 1.4731597 (162)	total: 6m 9s	remaining: 24m 4s
163:	learn: 1.4217477	test: 1.4728267	best: 1.4728267 (163)	total: 6m 11s	remaining: 23m 59s
164:	learn: 1.4213209	test: 1.4725431	best: 1.4725431 (164)	total: 6m 13s	remaining: 23m 56s
165:	learn: 1.4208652	test: 1.4722697	best: 1.4722697 (165)	total: 6m 15s	remaining: 23m 53s
166:	learn: 1.4204148	test: 1.4719644	best: 1.4719644 (166)	total: 6m 17s	remaining: 23m 50s
167:	learn: 1.4199109	test: 1.4717449	best: 1.4717449 (167)	total: 6m 19s	remaining: 23m 48s
168:	learn: 1.4193121	test: 1.4715298	best: 1.4715298 (168)	total: 6m 21s	remaining: 23m 46s
169:	learn: 1.4188003	test: 1.4712106	best: 1.4712106 (169)	total: 6m 24s	remaining: 23m 43s
170:	learn: 1.4184321	test: 1.4709270	best: 1.4709270 (170)	total: 6m 26s	remaining: 23m 40s
171:	learn: 1.4178546	test: 1.4703815	best: 1.4703815 (171)	total: 6m 28s	remaining: 23m 36s
172:	learn: 1.4173629	test: 1.4701657	best: 1.4701657 (172)	total: 6m 30s	remaining: 23m 34s
173:	learn: 1.4166971	test: 1.4697502	best: 1.4697502 (173)	total: 6m 32s	remaining: 23m 31s
174:	learn: 1.4163438	test: 1.4695324	best: 1.4695324 (174)	total: 6m 33s	remaining: 23m 26s
175:	learn: 1.4158407	test: 1.4692845	best: 1.4692845 (175)	total: 6m 35s	remaining: 23m 22s
176:	learn: 1.4154432	test: 1.4691050	best: 1.4691050 (176)	total: 6m 37s	remaining: 23m 20s
177:	learn: 1.4151137	test: 1.4688160	best: 1.4688160 (177)	total: 6m 39s	remaining: 23m 16s
178:	learn: 1.4145721	test: 1.4684820	best: 1.4684820 (178)	total: 6m 41s	remaining: 23m 14s
179:	learn: 1.4140479	test: 1.4679951	best: 1.4679951 (179)	total: 6m 43s	remaining: 23m 11s
180:	learn: 1.4135369	test: 1.4677330	best: 1.4677330 (180)	total: 6m 45s	remaining: 23m 7s
181:	learn: 1.4132165	test: 1.4672252	best: 1.4672252 (181)	total: 6m 47s	remaining: 23m 3s
182:	learn: 1.4126186	test: 1.4666289	best: 1.4666289 (182)	total: 6m 49s	remaining: 22m 59s
183:	learn: 1.4119483	test: 1.4660254	best: 1.4660254 (183)	total: 6m 50s	remaining: 22m 55s
184:	learn: 1.4115830	test: 1.4656658	best: 1.4656658 (184)	total: 6m 53s	remaining: 22m 53s
185:	learn: 1.4106307	test: 1.4650803	best: 1.4650803 (185)	total: 6m 55s	remaining: 22m 51s
186:	learn: 1.4101367	test: 1.4645329	best: 1.4645329 (186)	total: 6m 57s	remaining: 22m 49s
187:	learn: 1.4093912	test: 1.4636739	best: 1.4636739 (187)	total: 6m 59s	remaining: 22m 46s
188:	learn: 1.4090893	test: 1.4635193	best: 1.4635193 (188)	total: 7m 1s	remaining: 22m 42s
189:	learn: 1.4086320	test: 1.4631331	best: 1.4631331 (189)	total: 7m 3s	remaining: 22m 40s
190:	learn: 1.4078619	test: 1.4624785	best: 1.4624785 (190)	total: 7m 5s	remaining: 22m 37s
191:	learn: 1.4072249	test: 1.4618920	best: 1.4618920 (191)	total: 7m 8s	remaining: 22m 36s
192:	learn: 1.4063882	test: 1.4611011	best: 1.4611011 (192)	total: 7m 9s	remaining: 22m 32s
193:	learn: 1.4056000	test: 1.4603141	best: 1.4603141 (193)	total: 7m 11s	remaining: 22m 29s
194:	learn: 1.4051060	test: 1.4599510	best: 1.4599510 (194)	total: 7m 13s	remaining: 22m 26s
195:	learn: 1.4045388	test: 1.4594062	best: 1.4594062 (195)	total: 7m 16s	remaining: 22m 24s
196:	learn: 1.4041013	test: 1.4589492	best: 1.4589492 (196)	total: 7m 18s	remaining: 22m 21s
197:	learn: 1.4031978	test: 1.4580549	best: 1.4580549 (197)	total: 7m 20s	remaining: 22m 19s
198:	learn: 1.4022858	test: 1.4574356	best: 1.4574356 (198)	total: 7m 22s	remaining: 22m 15s
199:	learn: 1.4015288	test: 1.4568248	best: 1.4568248 (199)	total: 7m 24s	remaining: 22m 12s
200:	learn: 1.4009591	test: 1.4565179	best: 1.4565179 (200)	total: 7m 26s	remaining: 22m 10s
201:	learn: 1.4005199	test: 1.4561911	best: 1.4561911 (201)	total: 7m 28s	remaining: 22m 7s
202:	learn: 1.4000953	test: 1.4560270	best: 1.4560270 (202)	total: 7m 30s	remaining: 22m 5s
203:	learn: 1.3994668	test: 1.4553995	best: 1.4553995 (203)	total: 7m 32s	remaining: 22m 2s
204:	learn: 1.3992437	test: 1.4551315	best: 1.4551315 (204)	total: 7m 34s	remaining: 21m 59s
205:	learn: 1.3985764	test: 1.4546224	best: 1.4546224 (205)	total: 7m 36s	remaining: 21m 56s
206:	learn: 1.3981136	test: 1.4540045	best: 1.4540045 (206)	total: 7m 38s	remaining: 21m 53s
207:	learn: 1.3976238	test: 1.4532691	best: 1.4532691 (207)	total: 7m 40s	remaining: 21m 49s
208:	learn: 1.3969255	test: 1.4527101	best: 1.4527101 (208)	total: 7m 42s	remaining: 21m 46s
209:	learn: 1.3966567	test: 1.4522527	best: 1.4522527 (209)	total: 7m 43s	remaining: 21m 41s
210:	learn: 1.3962312	test: 1.4519836	best: 1.4519836 (210)	total: 7m 45s	remaining: 21m 38s
211:	learn: 1.3959606	test: 1.4517354	best: 1.4517354 (211)	total: 7m 47s	remaining: 21m 35s
212:	learn: 1.3954258	test: 1.4512548	best: 1.4512548 (212)	total: 7m 49s	remaining: 21m 32s
213:	learn: 1.3948616	test: 1.4506931	best: 1.4506931 (213)	total: 7m 51s	remaining: 21m 29s
214:	learn: 1.3942149	test: 1.4502687	best: 1.4502687 (214)	total: 7m 52s	remaining: 21m 26s
215:	learn: 1.3935150	test: 1.4498323	best: 1.4498323 (215)	total: 7m 55s	remaining: 21m 24s
216:	learn: 1.3927373	test: 1.4490978	best: 1.4490978 (216)	total: 7m 56s	remaining: 21m 21s
217:	learn: 1.3922998	test: 1.4490059	best: 1.4490059 (217)	total: 7m 58s	remaining: 21m 18s

2026/02/21 20:55:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

- Cat2 model scores-

    - f1-score: 0.4446.
    - recall score: 0.4250.
    - precision score: 0.5017.

- LightGBM Models' MLFlow run and training.

In [13]:
# Importing the libraries
from lightgbm import LGBMClassifier

In [14]:
# Starting the MLflow run
with mlflow.start_run(run_name='LGBMClassifier_1'):
    
    # Initializing the LGBMClassifier model
    light1 = LGBMClassifier(n_estimators=300,
                          max_depth=6,
                          learning_rate=0.1,
                          random_state=42,
                          class_weight=class_weights)
    
    # Fitting the model on the training data
    light1.fit(x_train, y_train, eval_set=[(x_test, y_test)], categorical_feature=cat_cols)
    
    # Predicting the ratings on the test data
    y_pred = light1.predict(x_test)
    
    # Evaluating the model performance
    f1 = f1_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    precision = precision_score(y_test, y_pred, average='weighted')
    
    # Logging the parameters and metrics to MLflow
    mlflow.log_param('model_name', 'LGBMClassifier')
    mlflow.log_param('n_estimators', 300)
    mlflow.log_param('max_depth', 6)
    mlflow.log_param('learning_rate', 0.1)
    mlflow.log_metric('f1', f1)
    mlflow.log_metric('recall', recall)
    mlflow.log_metric('precision', precision)

    # Logging the model to MLflow
    mlflow.lightgbm.log_model(light1, 'light1')

[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005876 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1793
[LightGBM] [Info] Number of data points in the train set: 37023, number of used features: 8
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/02/21 20:57:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/21 20:57:15 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization.The recommended safe alternative is the 'skops' format.

- Light1 model scores-
    
    - f1-score: 0.4301.
    - recall score: 0.4190.
    - precision score: 0.4487.

In [15]:
# Starting abither MLflow run with different parameters
with mlflow.start_run(run_name='LGBMClassifier_2'):
    
    # Initializing the LGBMClassifier model
    light2 = LGBMClassifier(n_estimators=800,
                          max_depth=8,
                          learning_rate=0.01,
                          random_state=42,
                          class_weight=class_weights)
    
    # Fitting the model on the training data
    light2.fit(x_train, y_train, eval_set=[(x_test, y_test)], categorical_feature=cat_cols)
    
    # Predicting the ratings on the test data
    y_pred = light2.predict(x_test)
    
    # Evaluating the model performance
    f1 = f1_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    precision = precision_score(y_test, y_pred, average='weighted')
    
    # Logging the parameters and metrics to MLflow
    mlflow.log_param('model_name', 'LGBMClassifier')
    mlflow.log_param('n_estimators', 800)
    mlflow.log_param('max_depth', 8)
    mlflow.log_param('learning_rate', 0.01)
    mlflow.log_metric('f1', f1)
    mlflow.log_metric('recall', recall)
    mlflow.log_metric('precision', precision)

    # Logging the model to MLflow
    mlflow.lightgbm.log_model(light2, 'light2')

[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006766 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1793
[LightGBM] [Info] Number of data points in the train set: 37023, number of used features: 8
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Info] Start training from score -1.609438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/02/21 20:59:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/21 20:59:04 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization.The recommended safe alternative is the 'skops' format.

- Light2 model scores-

    - f1-score: 0.4178.
    - recall score: 0.4022
    - precision score: 0.4469.

- From the MLFlow dashboard observations, it was concluded that the "cat2" model of CatBoostClassifier was the best performing model.

    We will now train this model on the full dataset of df_clf, and then save it for it to be used in the Streamlit app.

In [8]:
# Separating the features and the target variable for classification task
x = df_clf.drop('VisitMode', axis=1)
y = df_clf['VisitMode']

In [17]:
# Initializing the CatBoostClassifier model
cat_clf_final = CatBoostClassifier(iterations=800,
                              depth=8,
                              learning_rate=0.01,
                              loss_function='MultiClass',
                              class_weights=class_weights,
                              random_seed=42)

# Fitting the model on the training data
cat_clf_final.fit(x, y, cat_features=cat_features)

0:	learn: 1.6064218	total: 2.92s	remaining: 38m 54s
1:	learn: 1.6036152	total: 5.66s	remaining: 37m 37s
2:	learn: 1.6007800	total: 7.55s	remaining: 33m 24s
3:	learn: 1.5983649	total: 10.1s	remaining: 33m 28s
4:	learn: 1.5958658	total: 12.2s	remaining: 32m 19s
5:	learn: 1.5931141	total: 14.3s	remaining: 31m 32s
6:	learn: 1.5911580	total: 15s	remaining: 28m 21s
7:	learn: 1.5889102	total: 17s	remaining: 28m 7s
8:	learn: 1.5865801	total: 19.3s	remaining: 28m 17s
9:	learn: 1.5842227	total: 21.2s	remaining: 27m 51s
10:	learn: 1.5816429	total: 23.5s	remaining: 28m 3s
11:	learn: 1.5794124	total: 25.5s	remaining: 27m 51s
12:	learn: 1.5769951	total: 27.6s	remaining: 27m 51s
13:	learn: 1.5749774	total: 29.6s	remaining: 27m 41s
14:	learn: 1.5729025	total: 31.7s	remaining: 27m 37s
15:	learn: 1.5707146	total: 34s	remaining: 27m 47s
16:	learn: 1.5686483	total: 36.2s	remaining: 27m 45s
17:	learn: 1.5668433	total: 38.7s	remaining: 27m 59s
18:	learn: 1.5647717	total: 40.8s	remaining: 27m 57s
19:	learn: 1.5629110	total: 43.3s	remaining: 28m 7s
20:	learn: 1.5610175	total: 45.6s	remaining: 28m 10s
21:	learn: 1.5591614	total: 47.8s	remaining: 28m 10s
22:	learn: 1.5574151	total: 50.1s	remaining: 28m 10s
23:	learn: 1.5556783	total: 52s	remaining: 28m
24:	learn: 1.5543141	total: 54.3s	remaining: 28m 2s
25:	learn: 1.5522225	total: 56.5s	remaining: 28m 1s
26:	learn: 1.5505093	total: 58.9s	remaining: 28m 5s
27:	learn: 1.5487006	total: 1m	remaining: 28m 1s
28:	learn: 1.5472650	total: 1m 3s	remaining: 28m 1s
29:	learn: 1.5455658	total: 1m 5s	remaining: 27m 54s
30:	learn: 1.5440970	total: 1m 7s	remaining: 27m 48s
31:	learn: 1.5425817	total: 1m 9s	remaining: 27m 53s
32:	learn: 1.5407914	total: 1m 11s	remaining: 27m 47s
33:	learn: 1.5392977	total: 1m 13s	remaining: 27m 36s
34:	learn: 1.5378305	total: 1m 15s	remaining: 27m 35s
35:	learn: 1.5362731	total: 1m 17s	remaining: 27m 29s
36:	learn: 1.5349081	total: 1m 19s	remaining: 27m 20s
37:	learn: 1.5335477	total: 1m 21s	remaining: 27m 18s
38:	learn: 1.5323952	total: 1m 23s	remaining: 27m 16s
39:	learn: 1.5310308	total: 1m 25s	remaining: 27m 13s
40:	learn: 1.5297242	total: 1m 28s	remaining: 27m 11s
41:	learn: 1.5286507	total: 1m 30s	remaining: 27m 11s
42:	learn: 1.5271815	total: 1m 32s	remaining: 27m 7s
43:	learn: 1.5258758	total: 1m 34s	remaining: 27m 5s
44:	learn: 1.5246242	total: 1m 36s	remaining: 27m 4s
45:	learn: 1.5234063	total: 1m 38s	remaining: 27m 2s
46:	learn: 1.5220867	total: 1m 41s	remaining: 27m 5s
47:	learn: 1.5207787	total: 1m 43s	remaining: 27m 3s
48:	learn: 1.5195553	total: 1m 45s	remaining: 27m 3s
49:	learn: 1.5185231	total: 1m 48s	remaining: 27m 1s
50:	learn: 1.5174164	total: 1m 49s	remaining: 26m 55s
51:	learn: 1.5161402	total: 1m 52s	remaining: 26m 53s
52:	learn: 1.5150945	total: 1m 54s	remaining: 26m 53s
53:	learn: 1.5137864	total: 1m 56s	remaining: 26m 50s
54:	learn: 1.5124916	total: 1m 58s	remaining: 26m 45s
55:	learn: 1.5114143	total: 2m	remaining: 26m 41s
56:	learn: 1.5104505	total: 2m 2s	remaining: 26m 37s
57:	learn: 1.5095680	total: 2m 4s	remaining: 26m 34s
58:	learn: 1.5085739	total: 2m 6s	remaining: 26m 32s
59:	learn: 1.5073443	total: 2m 8s	remaining: 26m 29s
60:	learn: 1.5066126	total: 2m 10s	remaining: 26m 15s
61:	learn: 1.5058447	total: 2m 12s	remaining: 26m 19s
62:	learn: 1.5049484	total: 2m 14s	remaining: 26m 17s
63:	learn: 1.5041178	total: 2m 16s	remaining: 26m 15s
64:	learn: 1.5032620	total: 2m 19s	remaining: 26m 14s
65:	learn: 1.5022442	total: 2m 21s	remaining: 26m 11s
66:	learn: 1.5012999	total: 2m 23s	remaining: 26m 8s
67:	learn: 1.5004305	total: 2m 25s	remaining: 26m 4s
68:	learn: 1.4994866	total: 2m 27s	remaining: 26m 1s
69:	learn: 1.4982461	total: 2m 29s	remaining: 25m 59s
70:	learn: 1.4973887	total: 2m 31s	remaining: 25m 57s
71:	learn: 1.4963900	total: 2m 33s	remaining: 25m 51s
72:	learn: 1.4955651	total: 2m 35s	remaining: 25m 50s
73:	learn: 1.4946534	total: 2m 37s	remaining: 25m 47s
74:	learn: 1.4935258	total: 2m 39s	remaining: 25m 46s
75:	learn: 1.4926362	total: 2m 41s	remaining: 25m 42s
76:	learn: 1.4918854	total: 2m 44s	remaining: 25m 40s
77:	learn: 1.4910977	total: 2m 46s	remaining: 25m 39s
78:	learn: 1.4900783	total: 2m 48s	remaining: 25m 38s
79:	learn: 1.4890176	total: 2m 50s	remaining: 25m 37s
80:	learn: 1.4881246	total: 2m 52s	remaining: 25m 35s
81:	learn: 1.4876606	total: 2m 54s	remaining: 25m 25s
82:	learn: 1.4868506	total: 2m 56s	remaining: 25m 22s
83:	learn: 1.4862093	total: 2m 58s	remaining: 25m 19s
84:	learn: 1.4852698	total: 3m	remaining: 25m 14s
85:	learn: 1.4845054	total: 3m 2s	remaining: 25m 13s
86:	learn: 1.4837077	total: 3m 4s	remaining: 25m 14s
87:	learn: 1.4830294	total: 3m 6s	remaining: 25m 10s
88:	learn: 1.4822177	total: 3m 8s	remaining: 25m 9s
89:	learn: 1.4813721	total: 3m 10s	remaining: 25m 6s
90:	learn: 1.4806369	total: 3m 13s	remaining: 25m 5s
91:	learn: 1.4798351	total: 3m 15s	remaining: 25m 4s
92:	learn: 1.4789687	total: 3m 17s	remaining: 25m
93:	learn: 1.4779612	total: 3m 19s	remaining: 24m 56s
94:	learn: 1.4771437	total: 3m 21s	remaining: 24m 56s
95:	learn: 1.4764479	total: 3m 23s	remaining: 24m 55s
96:	learn: 1.4754597	total: 3m 25s	remaining: 24m 49s
97:	learn: 1.4746925	total: 3m 27s	remaining: 24m 47s
98:	learn: 1.4737993	total: 3m 29s	remaining: 24m 44s
99:	learn: 1.4729000	total: 3m 31s	remaining: 24m 41s
100:	learn: 1.4719678	total: 3m 33s	remaining: 24m 38s
101:	learn: 1.4713169	total: 3m 36s	remaining: 24m 38s
102:	learn: 1.4703431	total: 3m 38s	remaining: 24m 36s
103:	learn: 1.4695063	total: 3m 40s	remaining: 24m 34s
104:	learn: 1.4685720	total: 3m 42s	remaining: 24m 32s
105:	learn: 1.4679516	total: 3m 44s	remaining: 24m 30s
106:	learn: 1.4673244	total: 3m 47s	remaining: 24m 32s
107:	learn: 1.4666900	total: 3m 50s	remaining: 24m 33s
108:	learn: 1.4660615	total: 3m 53s	remaining: 24m 37s
109:	learn: 1.4653887	total: 3m 55s	remaining: 24m 35s
110:	learn: 1.4647089	total: 3m 57s	remaining: 24m 36s
111:	learn: 1.4638295	total: 4m	remaining: 24m 38s
112:	learn: 1.4629986	total: 4m 3s	remaining: 24m 38s
113:	learn: 1.4621788	total: 4m 5s	remaining: 24m 39s
114:	learn: 1.4615352	total: 4m 8s	remaining: 24m 41s
115:	learn: 1.4608510	total: 4m 11s	remaining: 24m 44s
116:	learn: 1.4601804	total: 4m 14s	remaining: 24m 47s
117:	learn: 1.4596349	total: 4m 17s	remaining: 24m 49s
118:	learn: 1.4590494	total: 4m 20s	remaining: 24m 52s
119:	learn: 1.4584142	total: 4m 23s	remaining: 24m 55s
120:	learn: 1.4577813	total: 4m 26s	remaining: 24m 55s
121:	learn: 1.4572197	total: 4m 29s	remaining: 24m 57s
122:	learn: 1.4564233	total: 4m 32s	remaining: 24m 58s
123:	learn: 1.4555010	total: 4m 34s	remaining: 24m 57s
124:	learn: 1.4547243	total: 4m 37s	remaining: 24m 56s
125:	learn: 1.4540305	total: 4m 40s	remaining: 24m 59s
126:	learn: 1.4527821	total: 4m 42s	remaining: 24m 57s
127:	learn: 1.4516234	total: 4m 45s	remaining: 25m 1s
128:	learn: 1.4505819	total: 4m 48s	remaining: 25m
129:	learn: 1.4497088	total: 4m 51s	remaining: 25m 1s
130:	learn: 1.4486348	total: 4m 53s	remaining: 24m 59s
131:	learn: 1.4476926	total: 4m 56s	remaining: 24m 58s
132:	learn: 1.4466799	total: 4m 59s	remaining: 25m
133:	learn: 1.4455572	total: 5m 2s	remaining: 25m 2s
134:	learn: 1.4445863	total: 5m 4s	remaining: 25m 2s
135:	learn: 1.4440557	total: 5m 7s	remaining: 25m 1s
136:	learn: 1.4431105	total: 5m 10s	remaining: 25m 1s
137:	learn: 1.4420468	total: 5m 13s	remaining: 25m 3s
138:	learn: 1.4410014	total: 5m 16s	remaining: 25m 5s
139:	learn: 1.4401750	total: 5m 19s	remaining: 25m 6s
140:	learn: 1.4393192	total: 5m 22s	remaining: 25m 8s
141:	learn: 1.4385296	total: 5m 25s	remaining: 25m 10s
142:	learn: 1.4377515	total: 5m 29s	remaining: 25m 13s
143:	learn: 1.4368524	total: 5m 32s	remaining: 25m 12s
144:	learn: 1.4360891	total: 5m 35s	remaining: 25m 14s
145:	learn: 1.4350684	total: 5m 38s	remaining: 25m 14s
146:	learn: 1.4344721	total: 5m 40s	remaining: 25m 12s
147:	learn: 1.4336697	total: 5m 42s	remaining: 25m 10s
148:	learn: 1.4327549	total: 5m 45s	remaining: 25m 10s
149:	learn: 1.4317771	total: 5m 48s	remaining: 25m 9s
150:	learn: 1.4308800	total: 5m 51s	remaining: 25m 10s
151:	learn: 1.4303609	total: 5m 54s	remaining: 25m 10s
152:	learn: 1.4296930	total: 5m 57s	remaining: 25m 11s
153:	learn: 1.4286450	total: 6m	remaining: 25m 11s
154:	learn: 1.4276503	total: 6m 2s	remaining: 25m 9s
155:	learn: 1.4268309	total: 6m 5s	remaining: 25m 10s
156:	learn: 1.4262989	total: 6m 9s	remaining: 25m 13s
157:	learn: 1.4259374	total: 6m 10s	remaining: 25m 5s
158:	learn: 1.4252158	total: 6m 13s	remaining: 25m 5s
159:	learn: 1.4242593	total: 6m 16s	remaining: 25m 4s
160:	learn: 1.4239099	total: 6m 19s	remaining: 25m 4s
161:	learn: 1.4233810	total: 6m 22s	remaining: 25m 5s
162:	learn: 1.4228612	total: 6m 25s	remaining: 25m 6s
163:	learn: 1.4221240	total: 6m 28s	remaining: 25m 6s
164:	learn: 1.4212089	total: 6m 30s	remaining: 25m 3s
165:	learn: 1.4203120	total: 6m 33s	remaining: 25m 2s
166:	learn: 1.4196693	total: 6m 37s	remaining: 25m 5s
167:	learn: 1.4189892	total: 6m 40s	remaining: 25m 5s
168:	learn: 1.4183783	total: 6m 43s	remaining: 25m 5s
169:	learn: 1.4177161	total: 6m 46s	remaining: 25m 6s
170:	learn: 1.4172728	total: 6m 49s	remaining: 25m 6s
171:	learn: 1.4170424	total: 6m 52s	remaining: 25m 6s
172:	learn: 1.4165136	total: 6m 55s	remaining: 25m 6s
173:	learn: 1.4160418	total: 6m 59s	remaining: 25m 8s
174:	learn: 1.4152491	total: 7m 1s	remaining: 25m 6s
175:	learn: 1.4146162	total: 7m 4s	remaining: 25m 5s
176:	learn: 1.4138118	total: 7m 7s	remaining: 25m 3s
177:	learn: 1.4131648	total: 7m 10s	remaining: 25m 3s
178:	learn: 1.4124429	total: 7m 12s	remaining: 25m
179:	learn: 1.4116426	total: 7m 15s	remaining: 24m 58s
180:	learn: 1.4112234	total: 7m 18s	remaining: 24m 59s
181:	learn: 1.4108253	total: 7m 21s	remaining: 25m
182:	learn: 1.4103499	total: 7m 24s	remaining: 24m 58s
183:	learn: 1.4097256	total: 7m 27s	remaining: 24m 59s
184:	learn: 1.4090500	total: 7m 30s	remaining: 24m 57s
185:	learn: 1.4086440	total: 7m 33s	remaining: 24m 58s
186:	learn: 1.4077117	total: 7m 36s	remaining: 24m 56s
187:	learn: 1.4069840	total: 7m 39s	remaining: 24m 54s
188:	learn: 1.4065389	total: 7m 42s	remaining: 24m 54s
189:	learn: 1.4060760	total: 7m 44s	remaining: 24m 52s
190:	learn: 1.4053763	total: 7m 47s	remaining: 24m 51s
191:	learn: 1.4047977	total: 7m 50s	remaining: 24m 50s
192:	learn: 1.4043291	total: 7m 54s	remaining: 24m 51s
193:	learn: 1.4037246	total: 7m 56s	remaining: 24m 49s
194:	learn: 1.4033937	total: 8m	remaining: 24m 49s
195:	learn: 1.4029108	total: 8m 3s	remaining: 24m 48s
196:	learn: 1.4023649	total: 8m 7s	remaining: 24m 51s
197:	learn: 1.4018252	total: 8m 9s	remaining: 24m 48s
198:	learn: 1.4013843	total: 8m 12s	remaining: 24m 47s
199:	learn: 1.4009958	total: 8m 16s	remaining: 24m 48s
200:	learn: 1.4004554	total: 8m 18s	remaining: 24m 46s
201:	learn: 1.4000447	total: 8m 22s	remaining: 24m 47s
202:	learn: 1.3994594	total: 8m 26s	remaining: 24m 49s
203:	learn: 1.3985966	total: 8m 28s	remaining: 24m 46s
204:	learn: 1.3980202	total: 8m 31s	remaining: 24m 45s
205:	learn: 1.3974953	total: 8m 34s	remaining: 24m 44s
206:	learn: 1.3971384	total: 8m 38s	remaining: 24m 45s
207:	learn: 1.3966342	total: 8m 41s	remaining: 24m 45s
208:	learn: 1.3962247	total: 8m 45s	remaining: 24m 44s
209:	learn: 1.3956473	total: 8m 48s	remaining: 24m 43s
210:	learn: 1.3950599	total: 8m 50s	remaining: 24m 41s
211:	learn: 1.3944814	total: 8m 53s	remaining: 24m 40s
212:	learn: 1.3938382	total: 8m 56s	remaining: 24m 38s
213:	learn: 1.3933211	total: 8m 59s	remaining: 24m 37s
214:	learn: 1.3926631	total: 9m 2s	remaining: 24m 36s
215:	learn: 1.3921931	total: 9m 5s	remaining: 24m 33s
216:	learn: 1.3916586	total: 9m 8s	remaining: 24m 32s
217:	learn: 1.3911331	total: 9m 11s	remaining: 24m 32s
218:	learn: 1.3908861	total: 9m 14s	remaining: 24m 31s
219:	learn: 1.3904016	total: 9m 17s	remaining: 24m 29s
220:	learn: 1.3897237	total: 9m 20s	remaining: 24m 28s
221:	learn: 1.3893260	total: 9m 23s	remaining: 24m 28s
222:	learn: 1.3886634	total: 9m 26s	remaining: 24m 26s
223:	learn: 1.3882955	total: 9m 30s	remaining: 24m 27s
224:	learn: 1.3878704	total: 9m 33s	remaining: 24m 26s
225:	learn: 1.3873825	total: 9m 36s	remaining: 24m 24s
226:	learn: 1.3870445	total: 9m 39s	remaining: 24m 23s
227:	learn: 1.3866972	total: 9m 42s	remaining: 24m 22s
228:	learn: 1.3861559	total: 9m 45s	remaining: 24m 19s
229:	learn: 1.3858622	total: 9m 46s	remaining: 24m 13s
230:	learn: 1.3854107	total: 9m 49s	remaining: 24m 10s
231:	learn: 1.3849040	total: 9m 51s	remaining: 24m 8s
232:	learn: 1.3846189	total: 9m 54s	remaining: 24m 7s
233:	learn: 1.3841519	total: 9m 57s	remaining: 24m 6s
234:	learn: 1.3837812	total: 10m	remaining: 24m 4s
235:	learn: 1.3832643	total: 10m 3s	remaining: 24m 2s
236:	learn: 1.3827121	total: 10m 6s	remaining: 24m
237:	learn: 1.3822552	total: 10m 10s	remaining: 24m
238:	learn: 1.3816672	total: 10m 12s	remaining: 23m 58s
239:	learn: 1.3814002	total: 10m 15s	remaining: 23m 57s
240:	learn: 1.3809298	total: 10m 19s	remaining: 23m 56s
241:	learn: 1.3803498	total: 10m 22s	remaining: 23m 54s
242:	learn: 1.3800403	total: 10m 25s	remaining: 23m 53s
243:	learn: 1.3795836	total: 10m 28s	remaining: 23m 51s
244:	learn: 1.3793231	total: 10m 31s	remaining: 23m 51s
245:	learn: 1.3788319	total: 10m 34s	remaining: 23m 49s
246:	learn: 1.3784302	total: 10m 37s	remaining: 23m 47s
247:	learn: 1.3779013	total: 10m 40s	remaining: 23m 45s
248:	learn: 1.3775964	total: 10m 43s	remaining: 23m 44s
249:	learn: 1.3772623	total: 10m 46s	remaining: 23m 42s
250:	learn: 1.3768420	total: 10m 49s	remaining: 23m 40s
251:	learn: 1.3764939	total: 10m 52s	remaining: 23m 38s
252:	learn: 1.3759164	total: 10m 54s	remaining: 23m 35s
253:	learn: 1.3753910	total: 10m 58s	remaining: 23m 34s
254:	learn: 1.3751978	total: 11m 1s	remaining: 23m 32s
255:	learn: 1.3748823	total: 11m 4s	remaining: 23m 32s
256:	learn: 1.3743946	total: 11m 7s	remaining: 23m 30s
257:	learn: 1.3739613	total: 11m 10s	remaining: 23m 28s
258:	learn: 1.3734772	total: 11m 13s	remaining: 23m 27s
259:	learn: 1.3729821	total: 11m 15s	remaining: 23m 23s
260:	learn: 1.3728217	total: 11m 18s	remaining: 23m 21s
261:	learn: 1.3724427	total: 11m 21s	remaining: 23m 19s
262:	learn: 1.3721175	total: 11m 24s	remaining: 23m 17s
263:	learn: 1.3718098	total: 11m 27s	remaining: 23m 15s
264:	learn: 1.3713166	total: 11m 30s	remaining: 23m 13s
265:	learn: 1.3710869	total: 11m 32s	remaining: 23m 10s
266:	learn: 1.3708032	total: 11m 35s	remaining: 23m 8s
267:	learn: 1.3704483	total: 11m 38s	remaining: 23m 6s
268:	learn: 1.3700593	total: 11m 41s	remaining: 23m 3s
269:	learn: 1.3697670	total: 11m 43s	remaining: 23m 1s
270:	learn: 1.3695627	total: 11m 46s	remaining: 22m 59s
271:	learn: 1.3691826	total: 11m 49s	remaining: 22m 57s
272:	learn: 1.3688186	total: 11m 52s	remaining: 22m 55s
273:	learn: 1.3681383	total: 11m 55s	remaining: 22m 52s
274:	learn: 1.3678489	total: 11m 58s	remaining: 22m 51s
275:	learn: 1.3674421	total: 12m	remaining: 22m 48s
276:	learn: 1.3671633	total: 12m 4s	remaining: 22m 47s
277:	learn: 1.3670020	total: 12m 7s	remaining: 22m 46s
278:	learn: 1.3667257	total: 12m 10s	remaining: 22m 43s
279:	learn: 1.3665789	total: 12m 12s	remaining: 22m 40s
280:	learn: 1.3661965	total: 12m 14s	remaining: 22m 37s
281:	learn: 1.3658943	total: 12m 18s	remaining: 22m 35s
282:	learn: 1.3654837	total: 12m 21s	remaining: 22m 33s
283:	learn: 1.3652304	total: 12m 23s	remaining: 22m 31s
284:	learn: 1.3651751	total: 12m 24s	remaining: 22m 25s
285:	learn: 1.3649342	total: 12m 27s	remaining: 22m 22s
286:	learn: 1.3645871	total: 12m 29s	remaining: 22m 20s
287:	learn: 1.3642490	total: 12m 33s	remaining: 22m 18s
288:	learn: 1.3638830	total: 12m 36s	remaining: 22m 17s
289:	learn: 1.3635875	total: 12m 39s	remaining: 22m 15s
290:	learn: 1.3632418	total: 12m 42s	remaining: 22m 13s
291:	learn: 1.3629321	total: 12m 45s	remaining: 22m 10s
292:	learn: 1.3625540	total: 12m 47s	remaining: 22m 8s
293:	learn: 1.3621124	total: 12m 50s	remaining: 22m 5s
294:	learn: 1.3618883	total: 12m 53s	remaining: 22m 3s
295:	learn: 1.3615123	total: 12m 56s	remaining: 22m 1s
296:	learn: 1.3612722	total: 12m 58s	remaining: 21m 59s
297:	learn: 1.3609975	total: 13m 2s	remaining: 21m 57s
298:	learn: 1.3607091	total: 13m 5s	remaining: 21m 55s
299:	learn: 1.3603689	total: 13m 8s	remaining: 21m 54s
300:	learn: 1.3600096	total: 13m 11s	remaining: 21m 51s
301:	learn: 1.3595190	total: 13m 14s	remaining: 21m 49s
302:	learn: 1.3591891	total: 13m 16s	remaining: 21m 47s
303:	learn: 1.3588029	total: 13m 19s	remaining: 21m 44s
304:	learn: 1.3584819	total: 13m 22s	remaining: 21m 42s
305:	learn: 1.3581074	total: 13m 25s	remaining: 21m 40s
306:	learn: 1.3579438	total: 13m 28s	remaining: 21m 37s
307:	learn: 1.3574818	total: 13m 30s	remaining: 21m 34s
308:	learn: 1.3571081	total: 13m 33s	remaining: 21m 33s
309:	learn: 1.3567012	total: 13m 36s	remaining: 21m 30s
310:	learn: 1.3563900	total: 13m 39s	remaining: 21m 28s
311:	learn: 1.3561279	total: 13m 42s	remaining: 21m 27s
312:	learn: 1.3557826	total: 13m 45s	remaining: 21m 24s
313:	learn: 1.3555339	total: 13m 49s	remaining: 21m 23s
314:	learn: 1.3551936	total: 13m 52s	remaining: 21m 21s
315:	learn: 1.3548614	total: 13m 54s	remaining: 21m 18s
316:	learn: 1.3547957	total: 13m 57s	remaining: 21m 15s
317:	learn: 1.3544774	total: 14m	remaining: 21m 13s
318:	learn: 1.3542873	total: 14m 3s	remaining: 21m 11s
319:	learn: 1.3540400	total: 14m 7s	remaining: 21m 10s
320:	learn: 1.3536879	total: 14m 9s	remaining: 21m 8s
321:	learn: 1.3533205	total: 14m 12s	remaining: 21m 6s
322:	learn: 1.3530252	total: 14m 16s	remaining: 21m 4s
323:	learn: 1.3527278	total: 14m 19s	remaining: 21m 2s
324:	learn: 1.3524479	total: 14m 22s	remaining: 21m
325:	learn: 1.3520869	total: 14m 25s	remaining: 20m 58s
326:	learn: 1.3518963	total: 14m 28s	remaining: 20m 56s
327:	learn: 1.3515539	total: 14m 31s	remaining: 20m 54s
328:	learn: 1.3513874	total: 14m 35s	remaining: 20m 52s
329:	learn: 1.3510634	total: 14m 38s	remaining: 20m 50s
330:	learn: 1.3506804	total: 14m 40s	remaining: 20m 48s
331:	learn: 1.3502396	total: 14m 43s	remaining: 20m 46s
332:	learn: 1.3498768	total: 14m 47s	remaining: 20m 44s
333:	learn: 1.3495324	total: 14m 50s	remaining: 20m 42s
334:	learn: 1.3493001	total: 14m 53s	remaining: 20m 39s
335:	learn: 1.3490302	total: 14m 56s	remaining: 20m 37s
336:	learn: 1.3487628	total: 14m 59s	remaining: 20m 35s
337:	learn: 1.3485006	total: 15m 2s	remaining: 20m 33s
338:	learn: 1.3480017	total: 15m 5s	remaining: 20m 31s
339:	learn: 1.3476673	total: 15m 9s	remaining: 20m 29s
340:	learn: 1.3475126	total: 15m 12s	remaining: 20m 28s
341:	learn: 1.3471750	total: 15m 15s	remaining: 20m 26s
342:	learn: 1.3470882	total: 15m 18s	remaining: 20m 24s
343:	learn: 1.3468971	total: 15m 21s	remaining: 20m 21s
344:	learn: 1.3467157	total: 15m 24s	remaining: 20m 18s
345:	learn: 1.3464419	total: 15m 27s	remaining: 20m 16s
346:	learn: 1.3462231	total: 15m 30s	remaining: 20m 14s
347:	learn: 1.3461666	total: 15m 33s	remaining: 20m 13s
348:	learn: 1.3461113	total: 15m 35s	remaining: 20m 8s
349:	learn: 1.3459444	total: 15m 38s	remaining: 20m 6s
350:	learn: 1.3457032	total: 15m 42s	remaining: 20m 5s
351:	learn: 1.3454639	total: 15m 44s	remaining: 20m 2s
352:	learn: 1.3452352	total: 15m 48s	remaining: 20m
353:	learn: 1.3449429	total: 15m 51s	remaining: 19m 58s
354:	learn: 1.3446914	total: 15m 54s	remaining: 19m 56s
355:	learn: 1.3444340	total: 15m 57s	remaining: 19m 54s
356:	learn: 1.3442386	total: 16m	remaining: 19m 52s
357:	learn: 1.3439428	total: 16m 3s	remaining: 19m 49s
358:	learn: 1.3437466	total: 16m 6s	remaining: 19m 47s
359:	learn: 1.3434571	total: 16m 9s	remaining: 19m 45s
360:	learn: 1.3431867	total: 16m 13s	remaining: 19m 43s
361:	learn: 1.3430222	total: 16m 16s	remaining: 19m 41s
362:	learn: 1.3428205	total: 16m 19s	remaining: 19m 38s
363:	learn: 1.3425300	total: 16m 22s	remaining: 19m 37s
364:	learn: 1.3424548	total: 16m 25s	remaining: 19m 34s
365:	learn: 1.3421606	total: 16m 29s	remaining: 19m 33s
366:	learn: 1.3418278	total: 16m 32s	remaining: 19m 30s

In [18]:
# Saving the trained final model
cat_clf_final.save_model('../models/cat_clf_final.cbm')

In [10]:
import joblib

# Storing the name of the columns of df_clf
clf_feature_cols = x.columns.tolist()

# Saving the feature columns
joblib.dump(clf_feature_cols, '../artifacts/clf_feature_cols.pkl')

# Saving cat_cols
joblib.dump(cat_cols, '../artifacts/clf_cat_cols.pkl')

['../artifacts/clf_cat_cols.pkl']